<?php

// Generated by Haxe 3.4.4
class haxe__EnumFlags_EnumFlags_Impl_ {
	public function __construct(){}
	static function _new($i = null) {
		if($i === null) {
			$i = 0;
		}
		$this1 = $i;
		return $this1;
	}
	static function has($this1, $v) {
		return ($this1 & 1 << $v->index) !== 0;
	}
	static function set($this1, $v) {
		$this1 = $this1 | 1 << $v->index;
	}
	static function hunset($this1, $v) {
		$this1 = $this1 & -1 - (1 << $v->index);
	}
	static function ofInt($i) {
		$this1 = $i;
		return $this1;
	}
	static function toInt($this1) {
		return $this1;
	}
	function __toString() { return 'haxe._EnumFlags.EnumFlags_Impl_'; }
}
