<?php

// Generated by Haxe 3.4.4
class ufront_mail__EmailAddress_EmailAddress_Impl_ {
	public function __construct(){}
	static function _new($email, $name = null) {
		if($name === null) {
			$name = "";
		}
		$this1 = null;
		$tmp = null;
		if($email !== null) {
			$tmp = !ufront_mail__EmailAddress_EmailAddress_Impl_::validate($email);
		} else {
			$tmp = true;
		}
		if($tmp) {
			throw new HException("Invalid email address: " . _hx_string_or_null($email));
		}
		$this1 = "" . _hx_string_or_null($email) . ";" . _hx_string_or_null($name);
		return $this1;
	}
	static function get_email($this1) {
		return _hx_substr($this1, 0, _hx_index_of($this1, ";", null));
	}
	static function get_username($this1) {
		return _hx_array_get(_hx_explode("@", ufront_mail__EmailAddress_EmailAddress_Impl_::get_email($this1)), 0);
	}
	static function get_domain($this1) {
		return _hx_array_get(_hx_explode("@", ufront_mail__EmailAddress_EmailAddress_Impl_::get_email($this1)), 1);
	}
	static function get_name($this1) {
		$split = _hx_index_of($this1, ";", null);
		if(strlen($this1) === $split + 1) {
			return null;
		} else {
			return _hx_substr($this1, _hx_index_of($this1, ";", null) + 1, null);
		}
	}
	static function fromString($email) {
		return ufront_mail__EmailAddress_EmailAddress_Impl_::_new($email, null);
	}
	static function toString($this1) {
		$tmp = null;
		if(ufront_mail__EmailAddress_EmailAddress_Impl_::get_name($this1) !== null) {
			$tmp = ufront_mail__EmailAddress_EmailAddress_Impl_::get_name($this1) !== "";
		} else {
			$tmp = false;
		}
		if($tmp) {
			$tmp1 = "\"" . _hx_string_or_null(ufront_mail__EmailAddress_EmailAddress_Impl_::get_name($this1)) . "\" <";
			return _hx_string_or_null($tmp1) . _hx_string_or_null(ufront_mail__EmailAddress_EmailAddress_Impl_::get_email($this1)) . ">";
		} else {
			return ufront_mail__EmailAddress_EmailAddress_Impl_::get_email($this1);
		}
	}
	static function validate($email) {
		$parts = _hx_explode("@", $email);
		if($parts->length !== 2) {
			return false;
		}
		$tmp = null;
		if(strlen($parts[0]) !== 0) {
			$tmp = _hx_index_of($parts[0], " ", null) > -1;
		} else {
			$tmp = true;
		}
		if($tmp) {
			return false;
		}
		$tmp1 = null;
		if(strlen($parts[1]) !== 0) {
			$tmp1 = _hx_index_of($parts[1], " ", null) > -1;
		} else {
			$tmp1 = true;
		}
		if($tmp1) {
			return false;
		}
		return true;
	}
	static $__properties__ = array("get_name" => "get_name","get_domain" => "get_domain","get_username" => "get_username","get_email" => "get_email");
	function __toString() { return 'ufront.mail._EmailAddress.EmailAddress_Impl_'; }
}
