<?php

// Generated by Haxe 3.4.4
class tink_io__IdealSink_IdealSink_Impl_ {
	public function __construct(){}
	static function inMemory($whenDone, $buffer = null) {
		return new tink_io__IdealSink_MemorySink($whenDone, $buffer);
	}
	function __toString() { return 'tink.io._IdealSink.IdealSink_Impl_'; }
}
