<?php

// Generated by Haxe 3.4.4
class ufront_mailer_UFMailer_HxMeta {
	public function __construct(){}
	static function __meta__() { $args = func_get_args(); return call_user_func_array(self::$__meta__, $args); }
	static $__meta__;
	function __toString() { return 'ufront.mailer.UFMailer_HxMeta'; }
}
ufront_mailer_UFMailer_HxMeta::$__meta__ = _hx_anonymous(array("obj" => _hx_anonymous(array("interface" => null))));
