<?php

// Generated by Haxe 3.4.2
class ufront_view__TemplateData_TemplateData_Impl_ {
	public function __construct(){}
	static function _new($obj = null) {
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		return $this1;
	}
	static function toObject($this1) {
		return $this1;
	}
	static function toMap($this1) {
		$ret = new haxe_ds_StringMap();
		{
			$_g = 0;
			$_g1 = Reflect::fields($this1);
			while($_g < $_g1->length) {
				$k = $_g1[$_g];
				$_g = $_g + 1;
				{
					$v = Reflect::field($this1, $k);
					$ret->set($k, $v);
					unset($v);
				}
				unset($k);
			}
		}
		return $ret;
	}
	static function toStringMap($this1) {
		return ufront_view__TemplateData_TemplateData_Impl_::toMap($this1);
	}
	static function get($this1, $key) {
		return Reflect::field($this1, $key);
	}
	static function exists($this1, $key) {
		return _hx_has_field($this1, $key);
	}
	static function set($this1, $key, $val) {
		$this1->{$key} = $val;
		$this2 = null;
		if($this1 !== null) {
			$this2 = $this1;
		} else {
			$this2 = _hx_anonymous(array());
		}
		return $this2;
	}
	static function array_set($this1, $key, $val) {
		$this1->{$key} = $val;
		return $val;
	}
	static function setMap($this1, $map) {
		{
			$k = $map->keys();
			while($k->hasNext()) {
				$k1 = $k->next();
				ufront_view__TemplateData_TemplateData_Impl_::set($this1, $k1, $map->get($k1));
				unset($k1);
			}
		}
		$this2 = null;
		if($this1 !== null) {
			$this2 = $this1;
		} else {
			$this2 = _hx_anonymous(array());
		}
		return $this2;
	}
	static function setObject($this1, $d) {
		{
			$_g = Type::typeof($d);
			switch($_g->index) {
			case 4:{
				$_g1 = 0;
				$_g11 = Reflect::fields($d);
				while($_g1 < $_g11->length) {
					$k = $_g11[$_g1];
					$_g1 = $_g1 + 1;
					ufront_view__TemplateData_TemplateData_Impl_::set($this1, $k, Reflect::field($d, $k));
					unset($k);
				}
			}break;
			case 6:{
				$cls = _hx_deref($_g)->params[0];
				{
					$_g2 = 0;
					$_g12 = Type::getInstanceFields($cls);
					while($_g2 < $_g12->length) {
						$k1 = $_g12[$_g2];
						$_g2 = $_g2 + 1;
						try {
							ufront_view__TemplateData_TemplateData_Impl_::set($this1, $k1, Reflect::getProperty($d, $k1));
						}catch(Exception $__hx__e) {
							$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
							$e = $_ex_;
							{
								try {
									ufront_view__TemplateData_TemplateData_Impl_::set($this1, $k1, Reflect::field($d, $k1));
								}catch(Exception $__hx__e) {
									$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
									$e1 = $_ex_;
									{}
								}
								unset($e1);
							}
						}
						unset($k1,$e);
					}
				}
			}break;
			default:{}break;
			}
		}
		$this2 = null;
		if($this1 !== null) {
			$this2 = $this1;
		} else {
			$this2 = _hx_anonymous(array());
		}
		return $this2;
	}
	static function fromMap($d) {
		$obj = _hx_anonymous(array());
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		$m = $this1;
		ufront_view__TemplateData_TemplateData_Impl_::setMap($m, $d);
		return $m;
	}
	static function fromStringMap($d) {
		return ufront_view__TemplateData_TemplateData_Impl_::fromMap($d);
	}
	static function fromMany($dataSets) {
		$obj = _hx_anonymous(array());
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		$combined = $this1;
		{
			$d = $dataSets->iterator();
			while($d->hasNext()) {
				$d1 = $d->next();
				if($d1 !== null) {
					if(Std::is($d1, _hx_qtype("haxe.ds.StringMap"))) {
						$map = $d1;
						ufront_view__TemplateData_TemplateData_Impl_::setMap($combined, $map);
						unset($map);
					} else {
						$obj1 = $d1;
						ufront_view__TemplateData_TemplateData_Impl_::setObject($combined, $obj1);
						unset($obj1);
					}
				}
				unset($d1);
			}
		}
		return $combined;
	}
	static function fromObject($d) {
		$obj = _hx_anonymous(array());
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		return ufront_view__TemplateData_TemplateData_Impl_::setObject($this1, $d);
	}
	function __toString() { return 'ufront.view._TemplateData.TemplateData_Impl_'; }
}
