<?php

// Generated by Haxe 3.4.4
class tink_streams__Stream_Maybe_Impl_ {
	public function __construct(){}
	static function _new($o) {
		$this1 = $o;
		return $this1;
	}
	static function hisSet($this1) {
		return $this1 !== null;
	}
	static function get($this1) {
		return $this1;
	}
	static function map($this1, $f) {
		if($this1 !== null) {
			$this2 = call_user_func_array($f, array($this1));
			return $this2;
		} else {
			return null;
		}
	}
	static function flatMap($this1, $f) {
		if($this1 !== null) {
			return call_user_func_array($f, array($this1));
		} else {
			return null;
		}
	}
	static function Some($v) {
		$this1 = $v;
		return $this1;
	}
	static function None() {
		return null;
	}
	function __toString() { return 'tink.streams._Stream.Maybe_Impl_'; }
}
