<?php

// Generated by Haxe 3.4.4
class tink_streams__Stream_Stream_Impl_ {
	public function __construct(){}
	static function later($f) {
		return new tink_streams__Stream_FutureStream($f);
	}
	static function ofIterator($i) {
		return new tink_streams_IteratorStream($i, null);
	}
	static function failure($e) {
		return tink_streams__Stream_Stream_Impl_::generate(array(new _hx_lambda(array(&$e), "tink_streams__Stream_Stream_Impl__0"), 'execute'));
	}
	static function generate($step) {
		return new tink_streams_Generator($step);
	}
	static function fold($this1, $start, $reduce) {
		return tink_core__Future_Future_Impl_::async(array(new _hx_lambda(array(&$reduce, &$start, &$this1), "tink_streams__Stream_Stream_Impl__1"), 'execute'), null);
	}
	static function foldAsync($this1, $start, $reduce) {
		return tink_core__Future_Future_Impl_::async(array(new _hx_lambda(array(&$reduce, &$start, &$this1), "tink_streams__Stream_Stream_Impl__2"), 'execute'), null);
	}
	static function collect($this1) {
		$ret = (new _hx_array(array()));
		return tink_core__Future_Future_Impl_::_tryMap($this1->hforEach(array(new _hx_lambda(array(&$ret), "tink_streams__Stream_Stream_Impl__3"), 'execute')), array(new _hx_lambda(array(&$ret), "tink_streams__Stream_Stream_Impl__4"), 'execute'));
	}
	static function concat($a, $b) {
		return tink_streams_ConcatStream::make((new _hx_array(array($a, $b))));
	}
	function __toString() { return 'tink.streams._Stream.Stream_Impl_'; }
}
function tink_streams__Stream_Stream_Impl__0(&$e) {
	{
		return new tink_core__Future_SyncFuture(new tink_core__Lazy_LazyConst(tink_streams_StreamStep::Fail($e)));
	}
}
function tink_streams__Stream_Stream_Impl__1(&$reduce, &$start, &$this1, $cb) {
	{
		$this1->hforEach(array(new _hx_lambda(array(&$reduce, &$start), "tink_streams__Stream_Stream_Impl__5"), 'execute'))->handle(array(new _hx_lambda(array(&$cb, &$start), "tink_streams__Stream_Stream_Impl__6"), 'execute'));
	}
}
function tink_streams__Stream_Stream_Impl__2(&$reduce, &$start, &$this1, $cb) {
	{
		$this1->forEachAsync(array(new _hx_lambda(array(&$reduce, &$start), "tink_streams__Stream_Stream_Impl__7"), 'execute'))->handle(array(new _hx_lambda(array(&$cb, &$start), "tink_streams__Stream_Stream_Impl__8"), 'execute'));
	}
}
function tink_streams__Stream_Stream_Impl__3(&$ret, $x) {
	{
		$ret->push($x);
		return true;
	}
}
function tink_streams__Stream_Stream_Impl__4(&$ret, $_) {
	{
		return $ret;
	}
}
function tink_streams__Stream_Stream_Impl__5(&$reduce, &$start, $x) {
	{
		$start = call_user_func_array($reduce, array($start, $x));
		return true;
	}
}
function tink_streams__Stream_Stream_Impl__6(&$cb, &$start, $o) {
	{
		$tmp = null;
		if($o->index === 1) {
			$e = _hx_deref($o)->params[0];
			$tmp = tink_core_Outcome::Failure($e);
		} else {
			$tmp = tink_core_Outcome::Success($start);
		}
		call_user_func_array($cb, array($tmp));
	}
}
function tink_streams__Stream_Stream_Impl__7(&$reduce, &$start, $x) {
	{
		$this2 = call_user_func_array($reduce, array($start, $x));
		$ret = $this2->map(array(new _hx_lambda(array(&$start), "tink_streams__Stream_Stream_Impl__9"), 'execute'));
		return $ret->gather();
	}
}
function tink_streams__Stream_Stream_Impl__8(&$cb, &$start, $o) {
	{
		$tmp = null;
		if($o->index === 1) {
			$e = _hx_deref($o)->params[0];
			$tmp = tink_core_Outcome::Failure($e);
		} else {
			$tmp = tink_core_Outcome::Success($start);
		}
		call_user_func_array($cb, array($tmp));
	}
}
function tink_streams__Stream_Stream_Impl__9(&$start, $v) {
	{
		$start = $v;
		return true;
	}
}
