<?php

// Generated by Haxe 3.4.4
class tink_streams__Stream_StreamMergeAsync_Impl_ {
	public function __construct(){}
	static function _new($data, $merger) {
		$this1 = new tink_streams_StreamMapFilterAsync($data, tink_streams__Stream_StreamMergeAsync_Impl_::lift($merger));
		return $this1;
	}
	static function lift($merger) {
		$buffer = (new _hx_array(array()));
		return array(new _hx_lambda(array(&$buffer, &$merger), "tink_streams__Stream_StreamMergeAsync_Impl__0"), 'execute');
	}
	function __toString() { return 'tink.streams._Stream.StreamMergeAsync_Impl_'; }
}
function tink_streams__Stream_StreamMergeAsync_Impl__0(&$buffer, &$merger, $x) {
	{
		$buffer->push($x);
		$this1 = call_user_func_array($merger, array($buffer));
		$ret = $this1->map(array(new _hx_lambda(array(&$buffer), "tink_streams__Stream_StreamMergeAsync_Impl__1"), 'execute'));
		return $ret->gather();
	}
}
function tink_streams__Stream_StreamMergeAsync_Impl__1(&$buffer, $o) {
	{
		switch($o->index) {
		case 0:{
			$v = _hx_deref($o)->params[0];
			$buffer = (new _hx_array(array()));
			$this2 = $v;
			return $this2;
		}break;
		case 1:{
			return null;
		}break;
		}
	}
}
