<?php

// Generated by Haxe 3.4.4
class tink_streams__Stream_StreamMap_Impl_ {
	public function __construct(){}
	static function _new($data, $map) {
		$this1 = new tink_streams_StreamMapFilter($data, tink_streams__Stream_StreamMap_Impl_::lift($map));
		return $this1;
	}
	static function lift($map) {
		return array(new _hx_lambda(array(&$map), "tink_streams__Stream_StreamMap_Impl__0"), 'execute');
	}
	function __toString() { return 'tink.streams._Stream.StreamMap_Impl_'; }
}
function tink_streams__Stream_StreamMap_Impl__0(&$map, $x) {
	{
		$this1 = call_user_func_array($map, array($x));
		return $this1;
	}
}
