<?php

// Generated by Haxe 3.4.4
class tink_streams__Stream_StreamMerge_Impl_ {
	public function __construct(){}
	static function _new($data, $merger) {
		$this1 = new tink_streams_StreamMapFilter($data, tink_streams__Stream_StreamMerge_Impl_::lift($merger));
		return $this1;
	}
	static function lift($merger) {
		$buffer = (new _hx_array(array()));
		return array(new _hx_lambda(array(&$buffer, &$merger), "tink_streams__Stream_StreamMerge_Impl__0"), 'execute');
	}
	function __toString() { return 'tink.streams._Stream.StreamMerge_Impl_'; }
}
function tink_streams__Stream_StreamMerge_Impl__0(&$buffer, &$merger, $x) {
	{
		$buffer->push($x);
		$_g = call_user_func_array($merger, array($buffer));
		switch($_g->index) {
		case 0:{
			$v = _hx_deref($_g)->params[0];
			$buffer = (new _hx_array(array()));
			$this1 = $v;
			return $this1;
		}break;
		case 1:{
			return null;
		}break;
		}
	}
}
