<?php

// Generated by Haxe 3.4.2
class ufront_core__ClassRef_ClassRef_Impl_ {
	public function __construct(){}
	static function _new($className) {
		$this1 = $className;
		return $this1;
	}
	static function toString($this1) {
		return $this1;
	}
	static function toClass($this1) {
		return Type::resolveClass($this1);
	}
	static function fromClass($v) {
		$this1 = Type::getClassName($v);
		return $this1;
	}
	static function fromClassName($className) {
		$this1 = $className;
		return $this1;
	}
	function __toString() { return 'ufront.core._ClassRef.ClassRef_Impl_'; }
}
