<?php

// Generated by Haxe 3.4.4
class haxe_macro_AnonStatus extends Enum {
	public static function AAbstractStatics($t) { return new haxe_macro_AnonStatus("AAbstractStatics", 6, array($t)); }
	public static function AClassStatics($t) { return new haxe_macro_AnonStatus("AClassStatics", 4, array($t)); }
	public static $AClosed;
	public static $AConst;
	public static function AEnumStatics($t) { return new haxe_macro_AnonStatus("AEnumStatics", 5, array($t)); }
	public static function AExtend($tl) { return new haxe_macro_AnonStatus("AExtend", 3, array($tl)); }
	public static $AOpened;
	public static $__constructors = array(6 => 'AAbstractStatics', 4 => 'AClassStatics', 0 => 'AClosed', 2 => 'AConst', 5 => 'AEnumStatics', 3 => 'AExtend', 1 => 'AOpened');
	}
haxe_macro_AnonStatus::$AClosed = new haxe_macro_AnonStatus("AClosed", 0);
haxe_macro_AnonStatus::$AConst = new haxe_macro_AnonStatus("AConst", 2);
haxe_macro_AnonStatus::$AOpened = new haxe_macro_AnonStatus("AOpened", 1);
