<?php

// Generated by Haxe 3.4.4
class tink_streams_StreamMapFilterAsync extends tink_streams_StreamBase {
	public function __construct($data, $transformer) {
		if(!php_Boot::$skip_constructor) {
		$this->data = $data;
		$this->transformer = $transformer;
	}}
	public $transformer;
	public $data;
	public function chain($transformer) {
		$_gthis = $this;
		return new tink_streams_StreamMapFilterAsync($this->data, array(new _hx_lambda(array(&$_gthis, &$transformer), "tink_streams_StreamMapFilterAsync_0"), 'execute'));
	}
	public function chainAsync($transformer) {
		$_gthis = $this;
		return new tink_streams_StreamMapFilterAsync($this->data, array(new _hx_lambda(array(&$_gthis, &$transformer), "tink_streams_StreamMapFilterAsync_1"), 'execute'));
	}
	public function forEachAsync($item) {
		$_gthis = $this;
		return $this->data->forEachAsync(array(new _hx_lambda(array(&$_gthis, &$item), "tink_streams_StreamMapFilterAsync_2"), 'execute'));
	}
	public function filterAsync($item) {
		return $this->chainAsync(tink_streams__Stream_StreamFilterAsync_Impl_::lift($item));
	}
	public function mapAsync($item) {
		return $this->chainAsync(tink_streams__Stream_StreamMapAsync_Impl_::lift($item));
	}
	public function mergeAsync($item) {
		return $this->chainAsync(tink_streams__Stream_StreamMergeAsync_Impl_::lift($item));
	}
	public function filter($item) {
		return $this->chain(tink_streams__Stream_StreamFilter_Impl_::lift($item));
	}
	public function map($item) {
		return $this->chain(tink_streams__Stream_StreamMap_Impl_::lift($item));
	}
	public function merge($item) {
		return $this->chain(tink_streams__Stream_StreamMerge_Impl_::lift($item));
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return 'tink.streams.StreamMapFilterAsync'; }
}
function tink_streams_StreamMapFilterAsync_0(&$_gthis, &$transformer, $i) {
	{
		$this1 = $_gthis->transformer($i);
		$ret = $this1->map(array(new _hx_lambda(array(&$transformer), "tink_streams_StreamMapFilterAsync_3"), 'execute'));
		return $ret->gather();
	}
}
function tink_streams_StreamMapFilterAsync_1(&$_gthis, &$transformer, $i) {
	{
		$this1 = $_gthis->transformer($i);
		$ret = $this1->flatMap(array(new _hx_lambda(array(&$transformer), "tink_streams_StreamMapFilterAsync_4"), 'execute'));
		return $ret->gather();
	}
}
function tink_streams_StreamMapFilterAsync_2(&$_gthis, &$item, $x) {
	{
		$this1 = $_gthis->transformer($x);
		$ret = $this1->flatMap(array(new _hx_lambda(array(&$item), "tink_streams_StreamMapFilterAsync_5"), 'execute'));
		return $ret;
	}
}
function tink_streams_StreamMapFilterAsync_3(&$transformer, $o) {
	{
		if($o !== null) {
			return call_user_func_array($transformer, array($o));
		} else {
			return null;
		}
	}
}
function tink_streams_StreamMapFilterAsync_4(&$transformer, $o) {
	{
		$v = $o;
		if($v !== null) {
			return call_user_func_array($transformer, array($v));
		} else {
			return new tink_core__Future_SyncFuture(new tink_core__Lazy_LazyConst(null));
		}
	}
}
function tink_streams_StreamMapFilterAsync_5(&$item, $x1) {
	{
		$v = $x1;
		if($v !== null) {
			return call_user_func_array($item, array($v));
		} else {
			return new tink_core__Future_SyncFuture(new tink_core__Lazy_LazyConst(true));
		}
	}
}
