<?php

// Generated by Haxe 3.4.4
class tink_core__Error_Stack_Impl_ {
	public function __construct(){}
	static function toString($this1) {
		return "Error stack not available. Compile with -D error_stack.";
	}
	function __toString() { return 'tink.core._Error.Stack_Impl_'; }
}
