<?php

// Generated by Haxe 3.4.4
class tink_io__IdealSource_CompoundSource extends tink_io_IdealSourceBase {
	public function __construct($parts) {
		if(!php_Boot::$skip_constructor) {
		$this->parts = $parts;
	}}
	public $parts;
	public function pipeSafelyTo($dest, $options = null) {
		$_gthis = $this;
		return tink_core__Future_Future_Impl_::async(array(new _hx_lambda(array(&$_gthis, &$dest, &$options), "tink_io__IdealSource_CompoundSource_0"), 'execute'), null);
	}
	public function closeSafely() {
		$_g = $this->parts;
		if($_g->length === 0) {
			return new tink_core__Future_SyncFuture(new tink_core__Lazy_LazyConst(tink_core_Noise::$Noise));
		} else {
			$_g1 = (new _hx_array(array()));
			{
				$_g11 = 0;
				$_g2 = $this->parts;
				while($_g11 < $_g2->length) {
					$p = $_g2[$_g11];
					$_g11 = $_g11 + 1;
					$_g1->push($p->closeSafely());
					unset($p);
				}
			}
			$this1 = tink_core__Future_Future_Impl_::ofMany($_g1, null);
			$ret = $this1->map(array(new _hx_lambda(array(), "tink_io__IdealSource_CompoundSource_1"), 'execute'));
			return $ret->gather();
		}
	}
	public function readSafely($into, $max = null) {
		if($max === null) {
			$max = 1073741824;
		}
		$_gthis = $this;
		$_g = $this->parts;
		if($_g->length === 0) {
			return new tink_core__Future_SyncFuture(new tink_core__Lazy_LazyConst(-1));
		} else {
			return tink_core__Future_Future_Impl_::async(array(new _hx_lambda(array(&$_gthis, &$into, &$max), "tink_io__IdealSource_CompoundSource_2"), 'execute'), null);
		}
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static function of($a, $b) {
		$_g = Std::instance($b, _hx_qtype("tink.io._IdealSource.CompoundSource"));
		$_g1 = Std::instance($a, _hx_qtype("tink.io._IdealSource.CompoundSource"));
		$tmp = null;
		if($_g1 === null) {
			if($_g === null) {
				$tmp = (new _hx_array(array($a, $b)));
			} else {
				$p = $_g->parts;
				$tmp = _hx_deref((new _hx_array(array($a))))->concat($p);
			}
		} else {
			if($_g === null) {
				$p1 = $_g1->parts;
				$tmp = $p1->concat((new _hx_array(array($b))));
			} else {
				$p11 = $_g1->parts;
				$p2 = $_g->parts;
				$tmp = $p11->concat($p2);
			}
		}
		return new tink_io__IdealSource_CompoundSource($tmp);
	}
	function __toString() { return 'tink.io._IdealSource.CompoundSource'; }
}
function tink_io__IdealSource_CompoundSource_0(&$_gthis, &$dest, &$options, $cb) {
	{
		$next = null;
		$next = array(new _hx_lambda(array(&$_gthis, &$cb, &$dest, &$next, &$options), "tink_io__IdealSource_CompoundSource_3"), 'execute');
		$next2 = $next;
		call_user_func($next2);
	}
}
function tink_io__IdealSource_CompoundSource_1($_) {
	{
		return tink_core_Noise::$Noise;
	}
}
function tink_io__IdealSource_CompoundSource_2(&$_gthis, &$into, &$max, $cb) {
	{
		$tmp = _hx_array_get($_gthis->parts, 0)->readSafely($into, 1073741824);
		$tmp->handle(array(new _hx_lambda(array(&$_gthis, &$cb, &$into, &$max), "tink_io__IdealSource_CompoundSource_4"), 'execute'));
	}
}
function tink_io__IdealSource_CompoundSource_3(&$_gthis, &$cb, &$dest, &$next, &$options) {
	{
		$_g = $_gthis->parts;
		if($_g->length === 0) {
			call_user_func_array($cb, array(tink_io_PipeResult::$AllWritten));
		} else {
			$v = $_g;
			$options1 = null;
			if($_gthis->parts->length === 1) {
				$options1 = $options;
			} else {
				$options1 = null;
			}
			$next1 = _hx_array_get($_gthis->parts, 0)->pipeSafelyTo($dest, $options1);
			$next1->handle(array(new _hx_lambda(array(&$_gthis, &$cb, &$next), "tink_io__IdealSource_CompoundSource_5"), 'execute'));
		}
	}
}
function tink_io__IdealSource_CompoundSource_4(&$_gthis, &$cb, &$into, &$max, $p) {
	{
		if($p < 0) {
			{
				$this1 = $_gthis->parts->shift();
				$this1->closeSafely();
			}
			$_gthis->readSafely($into, $max);
		} else {
			call_user_func_array($cb, array($p));
		}
	}
}
function tink_io__IdealSource_CompoundSource_5(&$_gthis, &$cb, &$next, $x) {
	{
		if($x->index === 0) {
			{
				$this1 = $_gthis->parts->shift();
				$this1->closeSafely();
			}
			call_user_func($next);
		} else {
			call_user_func_array($cb, array($x));
		}
	}
}
