<?php

// Generated by Haxe 3.4.4
class tink_io__IdealSource_IdealSource_Impl_ {
	public function __construct(){}
	static function read($this1, $into, $max = null) {
		if($max === null) {
			$max = 1073741824;
		}
		return $this1->readSafely($into, $max);
	}
	static function close($this1) {
		return $this1->closeSafely();
	}
	static function all($this1) {
		return $this1->allSafely();
	}
	static function skip($this1, $length) {
		$this2 = tink_io__Source_Source_Impl_::skip($this1, $length);
		return $this2->idealize(array(new _hx_lambda(array(), "tink_io__IdealSource_IdealSource_Impl__0"), 'execute'));
	}
	static function limit($this1, $length) {
		$this2 = tink_io__Source_Source_Impl_::limit($this1, $length);
		return $this2->idealize(array(new _hx_lambda(array(), "tink_io__IdealSource_IdealSource_Impl__1"), 'execute'));
	}
	static function prepend($this1, $other) {
		return tink_io__IdealSource_CompoundSource::of($other, $this1);
	}
	static function append($this1, $other) {
		return tink_io__IdealSource_CompoundSource::of($this1, $other);
	}
	static function pipeTo($this1, $dest, $options = null) {
		return $this1->pipeSafelyTo($dest, $options);
	}
	static function ofBytes($b, $offset = null) {
		if($offset === null) {
			$offset = 0;
		}
		if($b === null) {
			return tink_io_Empty::$instance;
		} else {
			return new tink_io_ByteSource($b, $offset);
		}
	}
	static function fromBytes($b) {
		$tmp = null;
		if($b === null) {
			$tmp = tink_io_Empty::$instance;
		} else {
			$tmp = new tink_io_ByteSource($b, 0);
		}
		return $tmp;
	}
	static function fromString($s) {
		if($s === null) {
			return tink_io_Empty::$instance;
		} else {
			$b = haxe_io_Bytes::ofString($s);
			if($b === null) {
				return tink_io_Empty::$instance;
			} else {
				return new tink_io_ByteSource($b, 0);
			}
		}
	}
	static function create() {
		return new tink_io_SyntheticIdealSource();
	}
	function __toString() { return 'tink.io._IdealSource.IdealSource_Impl_'; }
}
function tink_io__IdealSource_IdealSource_Impl__0($_) {
	{}
}
function tink_io__IdealSource_IdealSource_Impl__1($_) {
	{}
}
