<?php

// Generated by Haxe 3.4.2
class ufront_log_BrowserConsoleLogger implements ufront_app_UFLogHandler{
	public function __construct() {}
	public function log($ctx, $appMessages) {
		$tmp = null;
		if($ctx->response->get_contentType() === "text/html") {
			$tmp = !$ctx->response->isRedirect();
		} else {
			$tmp = false;
		}
		if($tmp) {
			$results = (new _hx_array(array()));
			{
				$_g = 0;
				$_g1 = $ctx->messages;
				while($_g < $_g1->length) {
					$msg = $_g1[$_g];
					$_g = $_g + 1;
					$results->push(ufront_log_BrowserConsoleLogger::formatMessage($msg));
					unset($msg);
				}
			}
			if($results->length > 0) {
				$script = "\x0A<script type=\"text/javascript\">\x0A" . _hx_string_or_null($results->join("\x0A")) . "\x0A</script>";
				$newContent = ufront_web_result_CallJavascriptResult::insertScriptsBeforeBodyTag($ctx->response->getBuffer(), (new _hx_array(array($script))));
				$ctx->response->clearContent();
				$ctx->response->write($newContent);
			}
		}
		return ufront_core_SurpriseTools::success();
	}
	static function formatMessage($m) {
		$type = null;
		$_g = $m->type;
		switch($_g->index) {
		case 0:{
			$type = "log";
		}break;
		case 1:{
			$type = "info";
		}break;
		case 2:{
			$type = "warn";
		}break;
		case 3:{
			$type = "error";
		}break;
		}
		$extras = null;
		$extras1 = null;
		if(_hx_field($m, "pos") !== null) {
			$extras1 = $m->pos->customParams !== null;
		} else {
			$extras1 = false;
		}
		if($extras1) {
			$extras = ", " . _hx_string_or_null($m->pos->customParams->join(", "));
		} else {
			$extras = "";
		}
		$msg = "" . _hx_string_or_null($m->pos->className) . "." . _hx_string_or_null($m->pos->methodName) . "(" . _hx_string_rec($m->pos->lineNumber, "") . "): ";
		$msg1 = _hx_string_or_null($msg) . Std::string($m->msg) . _hx_string_or_null($extras);
		return "console." . _hx_string_or_null($type) . "(decodeURIComponent(\"" . _hx_string_or_null(rawurlencode($msg1)) . "\"))";
	}
	function __toString() { return 'ufront.log.BrowserConsoleLogger'; }
}
