<?php

// Generated by Haxe 3.4.4
class tink_await__LoopIterator_LoopIterator_Impl_ {
	public function __construct(){}
	static function fromIterable($i) {
		return $i->iterator();
	}
	function __toString() { return 'tink.await._LoopIterator.LoopIterator_Impl_'; }
}
