<?php

// Generated by Haxe 3.4.4
class tink_core__Lazy_Lazy_Impl_ {
	public function __construct(){}
	static function get($this1) {
		return $this1->get();
	}
	static function ofFunc($f) {
		return new tink_core__Lazy_LazyFunc($f);
	}
	static function map($this1, $f) {
		return $this1->map($f);
	}
	static function flatMap($this1, $f) {
		return $this1->flatMap($f);
	}
	static function ofConst($c) {
		return new tink_core__Lazy_LazyConst($c);
	}
	function __toString() { return 'tink.core._Lazy.Lazy_Impl_'; }
}
