<?php

// Generated by Haxe 3.4.4
class ufront_mail_EmailConstants {
	public function __construct(){}
	static $KOI8_R = "koi8-r";
	static $ISO_8859_1 = "iso-8859-1";
	static $US_ASCII = "us-ascii";
	static $UTF_8 = "utf-8";
	static $TEXT_HTML = "text/html";
	static $TEXT_PLAIN = "text/plain";
	function __toString() { return 'ufront.mail.EmailConstants'; }
}
