<?php

// Generated by Haxe 3.4.4
class tink_io_IdealSinkBase extends tink_io_SinkBase implements tink_io_IdealSinkObject{
	public function idealize($onError) {
		return $this;
	}
	public function writeSafely($from) {
		throw new HException("not implemented");
	}
	public function closeSafely() {
		return new tink_core__Future_SyncFuture(new tink_core__Lazy_LazyConst(tink_core_Noise::$Noise));
	}
	public function write($from) {
		$this1 = $this->writeSafely($from);
		$ret = $this1->map((property_exists("tink_core_Outcome", "Success") ? tink_core_Outcome::$Success: array("tink_core_Outcome", "Success")));
		return $ret->gather();
	}
	public function close() {
		$this1 = $this->closeSafely();
		$ret = $this1->map((property_exists("tink_core_Outcome", "Success") ? tink_core_Outcome::$Success: array("tink_core_Outcome", "Success")));
		return $ret->gather();
	}
	function __toString() { return 'tink.io.IdealSinkBase'; }
}
