<?php

// Generated by Haxe 3.4.4
class tink_io_IdealSourceObject_HxMeta {
	public function __construct(){}
	static function __meta__() { $args = func_get_args(); return call_user_func_array(self::$__meta__, $args); }
	static $__meta__;
	function __toString() { return 'tink.io.IdealSourceObject_HxMeta'; }
}
tink_io_IdealSourceObject_HxMeta::$__meta__ = _hx_anonymous(array("obj" => _hx_anonymous(array("interface" => null))));
