<?php

// Generated by Haxe 3.4.4
class tink_io_PipeResult extends Enum {
	public static $AllWritten;
	public static $SinkEnded;
	public static function SinkFailed($e) { return new tink_io_PipeResult("SinkFailed", 1, array($e)); }
	public static function SourceFailed($e) { return new tink_io_PipeResult("SourceFailed", 3, array($e)); }
	public static $__constructors = array(0 => 'AllWritten', 2 => 'SinkEnded', 1 => 'SinkFailed', 3 => 'SourceFailed');
	}
tink_io_PipeResult::$AllWritten = new tink_io_PipeResult("AllWritten", 0);
tink_io_PipeResult::$SinkEnded = new tink_io_PipeResult("SinkEnded", 2);
