<?php

// Generated by Haxe 3.4.4
class tink_io_StdSink extends tink_io_SinkBase {
	public function __construct($name, $target, $worker = null) {
		if(!php_Boot::$skip_constructor) {
		$this->name = $name;
		$this->target = $target;
		$this->worker = tink_io__Worker_Worker_Impl_::ensure($worker);
	}}
	public $name;
	public $target;
	public $worker;
	public function write($from) {
		$_gthis = $this;
		$tmp = $this->worker;
		return tink_io__Worker_Worker_Impl_::work($tmp, new tink_core__Lazy_LazyFunc(array(new _hx_lambda(array(&$_gthis, &$from), "tink_io_StdSink_0"), 'execute')));
	}
	public function close() {
		$_gthis = $this;
		$tmp = $this->worker;
		return tink_io__Worker_Worker_Impl_::work($tmp, new tink_core__Lazy_LazyFunc(array(new _hx_lambda(array(&$_gthis), "tink_io_StdSink_1"), 'execute')));
	}
	public function toString() {
		return $this->name;
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return $this->toString(); }
}
function tink_io_StdSink_0(&$_gthis, &$from) {
	{
		$ret = $from->tryWritingTo($_gthis->name, $_gthis->target, null);
		$_gthis->target->flush();
		return $ret;
	}
}
function tink_io_StdSink_1(&$_gthis) {
	{
		$tmp1 = tink_core_TypedError::reporter(null, "Failed to close " . _hx_string_or_null($_gthis->name), _hx_anonymous(array("fileName" => "Sink.hx", "lineNumber" => 159, "className" => "tink.io.StdSink", "methodName" => "close")));
		return tink_core_TypedError::catchExceptions(array(new _hx_lambda(array(&$_gthis), "tink_io_StdSink_2"), 'execute'), $tmp1, _hx_anonymous(array("fileName" => "Sink.hx", "lineNumber" => 154, "className" => "tink.io.StdSink", "methodName" => "close")));
	}
}
function tink_io_StdSink_2(&$_gthis) {
	{
		$_gthis->target->close();
		return tink_core_Noise::$Noise;
	}
}
