<?php

// Generated by Haxe 3.4.4
class ufront_web_url_filter_UFUrlFilter_HxMeta {
	public function __construct(){}
	static function __meta__() { $args = func_get_args(); return call_user_func_array(self::$__meta__, $args); }
	static $__meta__;
	function __toString() { return 'ufront.web.url.filter.UFUrlFilter_HxMeta'; }
}
ufront_web_url_filter_UFUrlFilter_HxMeta::$__meta__ = _hx_anonymous(array("obj" => _hx_anonymous(array("interface" => null))));
