<?php

// Generated by Haxe 3.4.4
class tink_io__Buffer_Mutex {
	public function __construct() {}
	public function synchronized($f) {
		return call_user_func($f);
	}
	function __toString() { return 'tink.io._Buffer.Mutex'; }
}
