<?php

// Generated by Haxe 3.4.4
class smtpmailer_AddressTools {
	public function __construct(){}
	static function sanitizeAddress($address) {
		if(_hx_index_of($address, "<", null) > -1) {
			return $address;
		} else {
			return "<" . _hx_string_or_null($address) . ">";
		}
	}
	function __toString() { return 'smtpmailer.AddressTools'; }
}
