<?php

// Generated by Haxe 3.4.4
class smtpmailer_Secure extends Enum {
	public static $Auto;
	public static $No;
	public static $Ssl;
	public static $StartTls;
	public static $__constructors = array(0 => 'Auto', 1 => 'No', 2 => 'Ssl', 3 => 'StartTls');
	}
smtpmailer_Secure::$Auto = new smtpmailer_Secure("Auto", 0);
smtpmailer_Secure::$No = new smtpmailer_Secure("No", 1);
smtpmailer_Secure::$Ssl = new smtpmailer_Secure("Ssl", 2);
smtpmailer_Secure::$StartTls = new smtpmailer_Secure("StartTls", 3);
