<?php

// Generated by Haxe 3.4.4
class smtpmailer_SmtpMailer {
	public function __construct($connection) {
		if(!php_Boot::$skip_constructor) {
		$this->processing = false;
		$this->queue = (new _hx_array(array()));
		$this->parser = new smtpmailer_LineParser();
		$this->connected = false;
		if($connection->secure === null) {
			$connection->secure = smtpmailer_Secure::$Auto;
		}
		$this->connection = $connection;
	}}
	public $socket;
	public $source;
	public $connection;
	public $connected;
	public $options;
	public $parser;
	public $queue;
	public $processing;
	public function send($email) {
		$trigger = new tink_core_FutureTrigger();
		$tmp = $this->queue;
		$this1 = new tink_core_MPair($email, $trigger);
		$tmp->push($this1);
		$this->processQueue();
		return $trigger;
	}
	public function processQueue() {
		$_gthis = $this;
		if(!$this->processing) {
			$this->processing = true;
			$__doCount = 0;
			$__t2_break = array(new _hx_lambda(array(&$_gthis), "smtpmailer_SmtpMailer_0"), 'execute');
			$__t2_continue = null;
			$__t2_continue = array(new _hx_lambda(array(&$__doCount, &$__t2_break, &$__t2_continue, &$_gthis), "smtpmailer_SmtpMailer_1"), 'execute');
			$__t2_continue1 = $__t2_continue;
			call_user_func($__t2_continue1);
		}
	}
	public function sendMessage($email) {
		$_gthis = $this;
		return tink_core__Future_Future_Impl_::async(array(new _hx_lambda(array(&$_gthis, &$email), "smtpmailer_SmtpMailer_2"), 'execute'), null);
	}
	public function connect() {
		$_gthis = $this;
		return tink_core__Future_Future_Impl_::async(array(new _hx_lambda(array(&$_gthis), "smtpmailer_SmtpMailer_3"), 'execute'), null);
	}
	public function startTls() {
		$_gthis = $this;
		return tink_core__Future_Future_Impl_::async(array(new _hx_lambda(array(&$_gthis), "smtpmailer_SmtpMailer_4"), 'execute'), null);
	}
	public function auth() {
		$_gthis = $this;
		return tink_core__Future_Future_Impl_::async(array(new _hx_lambda(array(&$_gthis), "smtpmailer_SmtpMailer_5"), 'execute'), null);
	}
	public function hasOption($tokens) {
		{
			$_g = 0;
			$_g1 = $this->options;
			while($_g < $_g1->length) {
				$option = $_g1[$_g];
				$_g = $_g + 1;
				$matches = true;
				{
					$_g2 = 0;
					while($_g2 < $tokens->length) {
						$token = $tokens[$_g2];
						$_g2 = $_g2 + 1;
						$tmp = strtolower($option);
						if(_hx_index_of($tmp, strtolower($token), null) === -1) {
							$matches = false;
						}
						unset($token,$tmp);
					}
					unset($_g2);
				}
				if($matches) {
					return true;
				}
				unset($option,$matches);
			}
		}
		return false;
	}
	public function getOptions() {
		$_gthis = $this;
		return tink_core__Future_Future_Impl_::async(array(new _hx_lambda(array(&$_gthis), "smtpmailer_SmtpMailer_6"), 'execute'), null);
	}
	public function writeLine($line) {
		$_gthis = $this;
		return tink_core__Future_Future_Impl_::async(array(new _hx_lambda(array(&$_gthis, &$line), "smtpmailer_SmtpMailer_7"), 'execute'), null);
	}
	public function hasCode($line, $code) {
		$str = Std::string($code);
		return _hx_substr($line, 0, strlen($str)) === $str;
	}
	public function readLine($expectedStatus) {
		$_gthis = $this;
		return tink_core__Future_Future_Impl_::async(array(new _hx_lambda(array(&$_gthis, &$expectedStatus), "smtpmailer_SmtpMailer_8"), 'execute'), null);
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static function __meta__() { $args = func_get_args(); return call_user_func_array(self::$__meta__, $args); }
	static $__meta__;
	function __toString() { return 'smtpmailer.SmtpMailer'; }
}
smtpmailer_SmtpMailer::$__meta__ = _hx_anonymous(array("obj" => _hx_anonymous(array("await" => null)), "fields" => _hx_anonymous(array("processQueue" => _hx_anonymous(array("await" => null)), "sendMessage" => _hx_anonymous(array("async" => null)), "connect" => _hx_anonymous(array("async" => null)), "startTls" => _hx_anonymous(array("async" => null)), "auth" => _hx_anonymous(array("async" => null)), "getOptions" => _hx_anonymous(array("async" => null)), "writeLine" => _hx_anonymous(array("async" => null)), "readLine" => _hx_anonymous(array("async" => null))))));
function smtpmailer_SmtpMailer_0(&$_gthis) {
	{
		$_gthis->processing = false;
	}
}
function smtpmailer_SmtpMailer_1(&$__doCount, &$__t2_break, &$__t2_continue, &$_gthis) {
	{
		$__do = array(new _hx_lambda(array(&$__doCount, &$__t2_continue, &$_gthis), "smtpmailer_SmtpMailer_9"), 'execute');
		if($_gthis->queue->length > 0) {
			call_user_func($__do);
		} else {
			call_user_func($__t2_break);
		}
	}
}
function smtpmailer_SmtpMailer_2(&$_gthis, &$email, $__return) {
	{
		try {
			$encoded = smtpmailer_MultipartEncoder::encode($email);
			$__t9 = array(new _hx_lambda(array(&$__return, &$_gthis), "smtpmailer_SmtpMailer_10"), 'execute');
			try {
				$this1 = $_gthis->connect();
				$this1->handle(array(new _hx_lambda(array(&$__return, &$__t9, &$_gthis, &$email, &$encoded), "smtpmailer_SmtpMailer_11"), 'execute'));
			}catch(Exception $__hx__e) {
				$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
				$e24 = $_ex_;
				{
					call_user_func_array($__t9, array($e24));
				}
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e25 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e25)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_3(&$_gthis, $__return) {
	{
		try {
			if($_gthis->connected) {
				call_user_func_array($__return, array(tink_core_Outcome::Success(tink_core_Noise::$Noise)));
				return;
			}
			$_g = $_gthis->connection->secure;
			$p = null;
			switch($_g->index) {
			case 0:{
				if($_gthis->connection->port === 465) {
					$p = new asys_ssl_Socket();
				} else {
					$p = new asys_net_Socket();
				}
			}break;
			case 2:{
				$p = new asys_ssl_Socket();
			}break;
			case 1:case 3:{
				$p = new asys_net_Socket();
			}break;
			}
			$_gthis->socket = $p;
			$start = "";
			$__t24 = array(new _hx_lambda(array(&$__return, &$_gthis, &$start), "smtpmailer_SmtpMailer_12"), 'execute');
			$__t36 = array(new _hx_lambda(array(&$__return), "smtpmailer_SmtpMailer_13"), 'execute');
			try {
				$_gthis1 = $_gthis->socket;
				$_gthis1->connect(new asys_net_Host($_gthis->connection->host), $_gthis->connection->port)->handle(array(new _hx_lambda(array(&$__t24, &$__t36, &$_gthis, &$start), "smtpmailer_SmtpMailer_14"), 'execute'));
			}catch(Exception $__hx__e) {
				$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
				$e14 = $_ex_;
				{
					call_user_func_array($__t36, array($e14));
				}
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e15 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e15)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_4(&$_gthis, $__return) {
	{
		try {
			$this1 = $_gthis->writeLine("STARTTLS");
			$this1->handle(array(new _hx_lambda(array(&$__return, &$_gthis), "smtpmailer_SmtpMailer_15"), 'execute'));
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e8 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e8)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_5(&$_gthis, $__return) {
	{
		try {
			$this1 = $_gthis->writeLine("AUTH LOGIN");
			$this1->handle(array(new _hx_lambda(array(&$__return, &$_gthis), "smtpmailer_SmtpMailer_16"), 'execute'));
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e12 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e12)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_6(&$_gthis, $__return) {
	{
		try {
			$options = (new _hx_array(array()));
			$__doCount = 0;
			$__t49_break = array(new _hx_lambda(array(&$__return, &$options), "smtpmailer_SmtpMailer_17"), 'execute');
			$__t49_continue = null;
			$__t49_continue = array(new _hx_lambda(array(&$__doCount, &$__return, &$__t49_break, &$__t49_continue, &$_gthis, &$options), "smtpmailer_SmtpMailer_18"), 'execute');
			$__t49_continue1 = $__t49_continue;
			call_user_func($__t49_continue1);
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e2 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e2)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_7(&$_gthis, &$line, $__return) {
	{
		try {
			$_gthis->source = $_gthis->socket->input;
			$this1 = tink_io__IdealSource_IdealSource_Impl_::fromString(_hx_string_or_null($line) . "\x0D\x0A");
			$this2 = $_gthis->socket->output;
			$p = $this1->pipeSafelyTo($this2, null);
			$p->handle(array(new _hx_lambda(array(&$__return), "smtpmailer_SmtpMailer_19"), 'execute'));
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e2 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e2)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_8(&$_gthis, &$expectedStatus, $__return) {
	{
		try {
			if($_gthis->source === null) {
				$p = tink_core_Outcome::Failure(tink_core_TypedError::withData(null, "Error", "Could not read from stream", _hx_anonymous(array("fileName" => "SmtpMailer.hx", "lineNumber" => 213, "className" => "smtpmailer.SmtpMailer", "methodName" => "readLine"))));
				call_user_func_array($__return, array($p));
				return;
			}
			$p1 = $_gthis->source->parse($_gthis->parser);
			$p1->handle(array(new _hx_lambda(array(&$__return, &$_gthis, &$expectedStatus), "smtpmailer_SmtpMailer_20"), 'execute'));
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e2 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e2)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_9(&$__doCount, &$__t2_continue, &$_gthis) {
	{
		$__doCount = $__doCount + 1;
		if($__doCount - 1 === 0) {
			while(true) {
				$pair = $_gthis->queue->shift();
				$email = $pair->a;
				$trigger = $pair->b;
				$__t3 = array(new _hx_lambda(array(&$__t2_continue), "smtpmailer_SmtpMailer_21"), 'execute');
				$__t5 = array(new _hx_lambda(array(&$__t3, &$trigger), "smtpmailer_SmtpMailer_22"), 'execute');
				try {
					$this1 = $_gthis->sendMessage($email);
					$this1->handle(array(new _hx_lambda(array(&$__t3, &$__t5, &$trigger), "smtpmailer_SmtpMailer_23"), 'execute'));
					unset($this1);
				}catch(Exception $__hx__e) {
					$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
					$e4 = $_ex_;
					{
						call_user_func_array($__t5, array($e4));
					}
				}
				$__doCount = $__doCount - 1;
				if(!($__doCount !== 0)) {
					break;
				}
				unset($trigger,$pair,$email,$e4,$__t5,$__t3);
			}
		}
	}
}
function smtpmailer_SmtpMailer_10(&$__return, &$_gthis, $e) {
	{
		try {
			throw new HException(_hx_field($e, "data"));
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e1 = $_ex_;
			{
				if($_gthis->connected) {
					$_gthis->socket->close();
					$_gthis->connected = false;
				}
				$__t91 = tink_core_Outcome::Failure(tink_core_TypedError::withData(null, "Error", $e1, _hx_anonymous(array("fileName" => "SmtpMailer.hx", "lineNumber" => 108, "className" => "smtpmailer.SmtpMailer", "methodName" => "sendMessage"))));
				call_user_func_array($__return, array($__t91));
				return;
			}
		}
	}
}
function smtpmailer_SmtpMailer_11(&$__return, &$__t9, &$_gthis, &$email, &$encoded, $__t10) {
	{
		try {
			$__t10_result = null;
			{
				$_g = tink_await_OutcomeTools::getOutcome($__t10, null);
				switch($_g->index) {
				case 0:{
					$v = _hx_deref($_g)->params[0];
					$__t10_result = $v;
				}break;
				case 1:{
					$e2 = _hx_deref($_g)->params[0];
					call_user_func_array($__t9, array($e2));
					return;
				}break;
				}
			}
			{
				$this2 = $_gthis->writeLine("MAIL from: " . _hx_string_or_null($email->from->address));
				$this2->handle(array(new _hx_lambda(array(&$__return, &$__t9, &$_gthis, &$email, &$encoded), "smtpmailer_SmtpMailer_24"), 'execute'));
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e23 = $_ex_;
			{
				call_user_func_array($__t9, array($e23));
			}
		}
	}
}
function smtpmailer_SmtpMailer_12(&$__return, &$_gthis, &$start) {
	{
		$command = null;
		$command1 = null;
		if(_hx_field($_gthis->connection, "auth") === null) {
			$command1 = _hx_index_of($start, "ESMTP", null) === -1;
		} else {
			$command1 = false;
		}
		if($command1) {
			$command = "HELO";
		} else {
			$command = "EHLO";
		}
		{
			$this1 = _hx_string_or_null($command) . " " . _hx_string_or_null(asys_net_Host::localhost());
			$this2 = $_gthis->writeLine($this1);
			$this2->handle(array(new _hx_lambda(array(&$__return, &$_gthis), "smtpmailer_SmtpMailer_25"), 'execute'));
		}
	}
}
function smtpmailer_SmtpMailer_13(&$__return, $e8) {
	{
		try {
			throw new HException(_hx_field($e8, "data"));
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e9 = $_ex_;
			{
				$__t361 = "Could not connect to host: " . Std::string($e9);
				$__t362 = tink_core_Outcome::Failure(tink_core_TypedError::withData(null, "Error", $__t361, _hx_anonymous(array("fileName" => "SmtpMailer.hx", "lineNumber" => 132, "className" => "smtpmailer.SmtpMailer", "methodName" => "connect"))));
				call_user_func_array($__return, array($__t362));
				return;
			}
		}
	}
}
function smtpmailer_SmtpMailer_14(&$__t24, &$__t36, &$_gthis, &$start, $__t37) {
	{
		try {
			$__t37_result = null;
			{
				$_g11 = tink_await_OutcomeTools::getOutcome($__t37, null);
				switch($_g11->index) {
				case 0:{
					$v4 = _hx_deref($_g11)->params[0];
					$__t37_result = $v4;
				}break;
				case 1:{
					$e10 = _hx_deref($_g11)->params[0];
					call_user_func_array($__t36, array($e10));
					return;
				}break;
				}
			}
			{
				$_gthis->socket->setTimeout(5);
				$_gthis->source = $_gthis->socket->input;
				{
					$this6 = $_gthis->readLine(220);
					$this6->handle(array(new _hx_lambda(array(&$__t24, &$__t36, &$start), "smtpmailer_SmtpMailer_26"), 'execute'));
				}
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e13 = $_ex_;
			{
				call_user_func_array($__t36, array($e13));
			}
		}
	}
}
function smtpmailer_SmtpMailer_15(&$__return, &$_gthis, $__t39) {
	{
		try {
			$__t39_result = null;
			{
				$_g = tink_await_OutcomeTools::getOutcome($__t39, null);
				switch($_g->index) {
				case 0:{
					$v = _hx_deref($_g)->params[0];
					$__t39_result = $v;
				}break;
				case 1:{
					$e = _hx_deref($_g)->params[0];
					call_user_func_array($__return, array(tink_core_Outcome::Failure($e)));
					return;
				}break;
				}
			}
			{
				$this2 = $_gthis->readLine(220);
				$this2->handle(array(new _hx_lambda(array(&$__return, &$_gthis), "smtpmailer_SmtpMailer_27"), 'execute'));
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e7 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e7)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_16(&$__return, &$_gthis, $__t43) {
	{
		try {
			$__t43_result = null;
			{
				$_g = tink_await_OutcomeTools::getOutcome($__t43, null);
				switch($_g->index) {
				case 0:{
					$v = _hx_deref($_g)->params[0];
					$__t43_result = $v;
				}break;
				case 1:{
					$e = _hx_deref($_g)->params[0];
					call_user_func_array($__return, array(tink_core_Outcome::Failure($e)));
					return;
				}break;
				}
			}
			{
				$this2 = $_gthis->readLine(334);
				$this2->handle(array(new _hx_lambda(array(&$__return, &$_gthis), "smtpmailer_SmtpMailer_28"), 'execute'));
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e11 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e11)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_17(&$__return, &$options) {
	{
		call_user_func_array($__return, array(tink_core_Outcome::Success($options)));
		return;
	}
}
function smtpmailer_SmtpMailer_18(&$__doCount, &$__return, &$__t49_break, &$__t49_continue, &$_gthis, &$options) {
	{
		$__do = array(new _hx_lambda(array(&$__doCount, &$__return, &$__t49_break, &$__t49_continue, &$_gthis, &$options), "smtpmailer_SmtpMailer_29"), 'execute');
		call_user_func($__do);
	}
}
function smtpmailer_SmtpMailer_19(&$__return, $__t53) {
	{
		try {
			$__t53_result = null;
			{
				$_g = tink_await_OutcomeTools::getOutcome(null, $__t53);
				switch($_g->index) {
				case 0:{
					$v = _hx_deref($_g)->params[0];
					$__t53_result = $v;
				}break;
				case 1:{
					$e = _hx_deref($_g)->params[0];
					call_user_func_array($__return, array(tink_core_Outcome::Failure($e)));
					return;
				}break;
				}
			}
			if($__t53_result->index === 0) {
				call_user_func_array($__return, array(tink_core_Outcome::Success(tink_core_Noise::$Noise)));
				return;
			} else {
				$p1 = tink_core_Outcome::Failure(tink_core_TypedError::withData(null, "Error", "Could not write to stream", _hx_anonymous(array("fileName" => "SmtpMailer.hx", "lineNumber" => 203, "className" => "smtpmailer.SmtpMailer", "methodName" => "writeLine"))));
				call_user_func_array($__return, array($p1));
				return;
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e1 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e1)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_20(&$__return, &$_gthis, &$expectedStatus, $__t54) {
	{
		try {
			$__t54_result = null;
			{
				$_g = tink_await_OutcomeTools::getOutcome($__t54, null);
				switch($_g->index) {
				case 0:{
					$v = _hx_deref($_g)->params[0];
					$__t54_result = $v;
				}break;
				case 1:{
					$e = _hx_deref($_g)->params[0];
					call_user_func_array($__return, array(tink_core_Outcome::Failure($e)));
					return;
				}break;
				}
			}
			$response = $__t54_result;
			$_gthis->source = $response->rest;
			$line = $response->data;
			if(!$_gthis->hasCode($line, $expectedStatus)) {
				$p2 = tink_core_Outcome::Failure(tink_core_TypedError::withData(null, "Error", $line, _hx_anonymous(array("fileName" => "SmtpMailer.hx", "lineNumber" => 218, "className" => "smtpmailer.SmtpMailer", "methodName" => "readLine"))));
				call_user_func_array($__return, array($p2));
				return;
			}
			call_user_func_array($__return, array(tink_core_Outcome::Success($line)));
			return;
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e1 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e1)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_21(&$__t2_continue) {
	{
		call_user_func($__t2_continue);
	}
}
function smtpmailer_SmtpMailer_22(&$__t3, &$trigger, $e) {
	{
		try {
			throw new HException(_hx_field($e, "data"));
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e1 = $_ex_;
			{
				$trigger->trigger(tink_core_Outcome::Failure($e1));
				call_user_func($__t3);
			}
		}
		return;
	}
}
function smtpmailer_SmtpMailer_23(&$__t3, &$__t5, &$trigger, $__t6) {
	{
		try {
			$__t6_result = null;
			{
				$_g = tink_await_OutcomeTools::getOutcome($__t6, null);
				switch($_g->index) {
				case 0:{
					$v = _hx_deref($_g)->params[0];
					$__t6_result = $v;
				}break;
				case 1:{
					$e2 = _hx_deref($_g)->params[0];
					throw new HException($e2->data);
				}break;
				}
			}
			{
				$result = $__t6_result;
				$trigger->trigger(tink_core_Outcome::Success(tink_core_Noise::$Noise));
				call_user_func($__t3);
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e3 = $_ex_;
			{
				call_user_func_array($__t5, array($e3));
			}
		}
	}
}
function smtpmailer_SmtpMailer_24(&$__return, &$__t9, &$_gthis, &$email, &$encoded, $__t11) {
	{
		try {
			$__t11_result = null;
			{
				$_g1 = tink_await_OutcomeTools::getOutcome($__t11, null);
				switch($_g1->index) {
				case 0:{
					$v1 = _hx_deref($_g1)->params[0];
					$__t11_result = $v1;
				}break;
				case 1:{
					$e3 = _hx_deref($_g1)->params[0];
					call_user_func_array($__t9, array($e3));
					return;
				}break;
				}
			}
			{
				$this3 = $_gthis->readLine(250);
				$this3->handle(array(new _hx_lambda(array(&$__return, &$__t9, &$_gthis, &$email, &$encoded), "smtpmailer_SmtpMailer_30"), 'execute'));
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e22 = $_ex_;
			{
				call_user_func_array($__t9, array($e22));
			}
		}
	}
}
function smtpmailer_SmtpMailer_25(&$__return, &$_gthis, $__t26) {
	{
		try {
			$__t26_result = null;
			{
				$_g1 = tink_await_OutcomeTools::getOutcome($__t26, null);
				switch($_g1->index) {
				case 0:{
					$v = _hx_deref($_g1)->params[0];
					$__t26_result = $v;
				}break;
				case 1:{
					$e = _hx_deref($_g1)->params[0];
					call_user_func_array($__return, array(tink_core_Outcome::Failure($e)));
					return;
				}break;
				}
			}
			{
				$this3 = $_gthis->getOptions();
				$this3->handle(array(new _hx_lambda(array(&$__return, &$_gthis), "smtpmailer_SmtpMailer_31"), 'execute'));
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e7 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e7)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_26(&$__t24, &$__t36, &$start, $__t38) {
	{
		try {
			$__t38_result = null;
			{
				$_g21 = tink_await_OutcomeTools::getOutcome($__t38, null);
				switch($_g21->index) {
				case 0:{
					$v5 = _hx_deref($_g21)->params[0];
					$__t38_result = $v5;
				}break;
				case 1:{
					$e11 = _hx_deref($_g21)->params[0];
					call_user_func_array($__t36, array($e11));
					return;
				}break;
				}
			}
			{
				$start = $__t38_result;
				call_user_func($__t24);
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e12 = $_ex_;
			{
				call_user_func_array($__t36, array($e12));
			}
		}
	}
}
function smtpmailer_SmtpMailer_27(&$__return, &$_gthis, $__t40) {
	{
		try {
			$__t40_result = null;
			{
				$_g1 = tink_await_OutcomeTools::getOutcome($__t40, null);
				switch($_g1->index) {
				case 0:{
					$v1 = _hx_deref($_g1)->params[0];
					$__t40_result = $v1;
				}break;
				case 1:{
					$e1 = _hx_deref($_g1)->params[0];
					call_user_func_array($__return, array(tink_core_Outcome::Failure($e1)));
					return;
				}break;
				}
			}
			{
				$_gthis->socket = asys_ssl_Socket::upgrade($_gthis->socket);
				{
					$this3 = "EHLO " . _hx_string_or_null(asys_net_Host::localhost());
					$this4 = $_gthis->writeLine($this3);
					$this4->handle(array(new _hx_lambda(array(&$__return, &$_gthis), "smtpmailer_SmtpMailer_32"), 'execute'));
				}
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e6 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e6)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_28(&$__return, &$_gthis, $__t44) {
	{
		try {
			$__t44_result = null;
			{
				$_g1 = tink_await_OutcomeTools::getOutcome($__t44, null);
				switch($_g1->index) {
				case 0:{
					$v1 = _hx_deref($_g1)->params[0];
					$__t44_result = $v1;
				}break;
				case 1:{
					$e1 = _hx_deref($_g1)->params[0];
					call_user_func_array($__return, array(tink_core_Outcome::Failure($e1)));
					return;
				}break;
				}
			}
			{
				$this3 = haxe_crypto_Base64::encode(haxe_io_Bytes::ofString($_gthis->connection->auth->username), null);
				$this4 = $_gthis->writeLine($this3);
				$this4->handle(array(new _hx_lambda(array(&$__return, &$_gthis), "smtpmailer_SmtpMailer_33"), 'execute'));
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e10 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e10)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_29(&$__doCount, &$__return, &$__t49_break, &$__t49_continue, &$_gthis, &$options) {
	{
		$__doCount = $__doCount + 1;
		if($__doCount - 1 === 0) {
			while(true) {
				$this1 = $_gthis->readLine(250);
				$this1->handle(array(new _hx_lambda(array(&$__return, &$__t49_break, &$__t49_continue, &$options), "smtpmailer_SmtpMailer_34"), 'execute'));
				$__doCount = $__doCount - 1;
				if(!($__doCount !== 0)) {
					break;
				}
				unset($this1);
			}
		}
	}
}
function smtpmailer_SmtpMailer_30(&$__return, &$__t9, &$_gthis, &$email, &$encoded, $__t12) {
	{
		try {
			$__t12_result = null;
			{
				$_g2 = tink_await_OutcomeTools::getOutcome($__t12, null);
				switch($_g2->index) {
				case 0:{
					$v2 = _hx_deref($_g2)->params[0];
					$__t12_result = $v2;
				}break;
				case 1:{
					$e4 = _hx_deref($_g2)->params[0];
					call_user_func_array($__t9, array($e4));
					return;
				}break;
				}
			}
			{
				$__iterator = $email->to->iterator();
				{
					$__doCount = 0;
					$__t13_break = array(new _hx_lambda(array(&$__return, &$__t9, &$_gthis, &$encoded), "smtpmailer_SmtpMailer_35"), 'execute');
					$__t13_continue = null;
					$__t13_continue = array(new _hx_lambda(array(&$__doCount, &$__iterator, &$__t13_break, &$__t13_continue, &$__t9, &$_gthis), "smtpmailer_SmtpMailer_36"), 'execute');
					$__t13_continue1 = $__t13_continue;
					call_user_func($__t13_continue1);
				}
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e21 = $_ex_;
			{
				call_user_func_array($__t9, array($e21));
			}
		}
	}
}
function smtpmailer_SmtpMailer_31(&$__return, &$_gthis, $__t27) {
	{
		try {
			$__t27_result = null;
			{
				$_g2 = tink_await_OutcomeTools::getOutcome($__t27, null);
				switch($_g2->index) {
				case 0:{
					$v1 = _hx_deref($_g2)->params[0];
					$__t27_result = $v1;
				}break;
				case 1:{
					$e1 = _hx_deref($_g2)->params[0];
					call_user_func_array($__return, array(tink_core_Outcome::Failure($e1)));
					return;
				}break;
				}
			}
			{
				$_gthis->options = $__t27_result;
				$__t28 = array(new _hx_lambda(array(&$__return, &$_gthis), "smtpmailer_SmtpMailer_37"), 'execute');
				{
					$_g31 = $_gthis->connection->secure;
					if($_g31 === null) {
						call_user_func($__t28);
					} else {
						switch($_g31->index) {
						case 0:case 3:{
							if($_gthis->hasOption((new _hx_array(array("starttls"))))) {
								$this5 = $_gthis->startTls();
								$this5->handle(array(new _hx_lambda(array(&$__return, &$__t28), "smtpmailer_SmtpMailer_38"), 'execute'));
							} else {
								call_user_func($__t28);
							}
						}break;
						default:{
							call_user_func($__t28);
						}break;
						}
					}
				}
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e6 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e6)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_32(&$__return, &$_gthis, $__t41) {
	{
		try {
			$__t41_result = null;
			{
				$_g2 = tink_await_OutcomeTools::getOutcome($__t41, null);
				switch($_g2->index) {
				case 0:{
					$v2 = _hx_deref($_g2)->params[0];
					$__t41_result = $v2;
				}break;
				case 1:{
					$e2 = _hx_deref($_g2)->params[0];
					call_user_func_array($__return, array(tink_core_Outcome::Failure($e2)));
					return;
				}break;
				}
			}
			{
				$this5 = $_gthis->getOptions();
				$this5->handle(array(new _hx_lambda(array(&$__return, &$_gthis), "smtpmailer_SmtpMailer_39"), 'execute'));
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e5 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e5)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_33(&$__return, &$_gthis, $__t45) {
	{
		try {
			$__t45_result = null;
			{
				$_g2 = tink_await_OutcomeTools::getOutcome($__t45, null);
				switch($_g2->index) {
				case 0:{
					$v2 = _hx_deref($_g2)->params[0];
					$__t45_result = $v2;
				}break;
				case 1:{
					$e2 = _hx_deref($_g2)->params[0];
					call_user_func_array($__return, array(tink_core_Outcome::Failure($e2)));
					return;
				}break;
				}
			}
			{
				$this5 = $_gthis->readLine(334);
				$this5->handle(array(new _hx_lambda(array(&$__return, &$_gthis), "smtpmailer_SmtpMailer_40"), 'execute'));
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e9 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e9)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_34(&$__return, &$__t49_break, &$__t49_continue, &$options, $__t50) {
	{
		try {
			$__t50_result = null;
			{
				$_g = tink_await_OutcomeTools::getOutcome($__t50, null);
				switch($_g->index) {
				case 0:{
					$v = _hx_deref($_g)->params[0];
					$__t50_result = $v;
				}break;
				case 1:{
					$e = _hx_deref($_g)->params[0];
					call_user_func_array($__return, array(tink_core_Outcome::Failure($e)));
					return;
				}break;
				}
			}
			$line = $__t50_result;
			$options->push($line);
			if(_hx_substr($line, 3, 1) === "-") {
				call_user_func($__t49_continue);
				return;
			}
			call_user_func($__t49_break);
			return;
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e1 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e1)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_35(&$__return, &$__t9, &$_gthis, &$encoded) {
	{
		$this4 = $_gthis->writeLine("DATA");
		$this4->handle(array(new _hx_lambda(array(&$__return, &$__t9, &$_gthis, &$encoded), "smtpmailer_SmtpMailer_41"), 'execute'));
	}
}
function smtpmailer_SmtpMailer_36(&$__doCount, &$__iterator, &$__t13_break, &$__t13_continue, &$__t9, &$_gthis) {
	{
		$__do = array(new _hx_lambda(array(&$__doCount, &$__iterator, &$__t13_continue, &$__t9, &$_gthis), "smtpmailer_SmtpMailer_42"), 'execute');
		if($__iterator->hasNext()) {
			call_user_func($__do);
		} else {
			call_user_func($__t13_break);
		}
	}
}
function smtpmailer_SmtpMailer_37(&$__return, &$_gthis) {
	{
		$__t30 = array(new _hx_lambda(array(&$__return, &$_gthis), "smtpmailer_SmtpMailer_43"), 'execute');
		if(_hx_field($_gthis->connection, "auth") !== null) {
			$__t32 = array(new _hx_lambda(array(&$__t30), "smtpmailer_SmtpMailer_44"), 'execute');
			if(!$_gthis->hasOption((new _hx_array(array("login", "auth"))))) {
				$__t281 = tink_core_Outcome::Failure(tink_core_TypedError::withData(null, "Error", "Server does not support auth login", _hx_anonymous(array("fileName" => "SmtpMailer.hx", "lineNumber" => 145, "className" => "smtpmailer.SmtpMailer", "methodName" => "connect"))));
				call_user_func_array($__return, array($__t281));
				return;
			} else {
				$this4 = $_gthis->auth();
				$this4->handle(array(new _hx_lambda(array(&$__return, &$__t32), "smtpmailer_SmtpMailer_45"), 'execute'));
			}
		} else {
			call_user_func($__t30);
		}
	}
}
function smtpmailer_SmtpMailer_38(&$__return, &$__t28, $__t35) {
	{
		try {
			$__t35_result = null;
			{
				$_g32 = tink_await_OutcomeTools::getOutcome($__t35, null);
				switch($_g32->index) {
				case 0:{
					$v3 = _hx_deref($_g32)->params[0];
					$__t35_result = $v3;
				}break;
				case 1:{
					$e4 = _hx_deref($_g32)->params[0];
					call_user_func_array($__return, array(tink_core_Outcome::Failure($e4)));
					return;
				}break;
				}
			}
			call_user_func($__t28);
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e5 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e5)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_39(&$__return, &$_gthis, $__t42) {
	{
		try {
			$__t42_result = null;
			{
				$_g3 = tink_await_OutcomeTools::getOutcome($__t42, null);
				switch($_g3->index) {
				case 0:{
					$v3 = _hx_deref($_g3)->params[0];
					$__t42_result = $v3;
				}break;
				case 1:{
					$e3 = _hx_deref($_g3)->params[0];
					call_user_func_array($__return, array(tink_core_Outcome::Failure($e3)));
					return;
				}break;
				}
			}
			$_gthis->options = $__t42_result;
			call_user_func_array($__return, array(tink_core_Outcome::Success(tink_core_Noise::$Noise)));
			return;
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e4 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e4)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_40(&$__return, &$_gthis, $__t46) {
	{
		try {
			$__t46_result = null;
			{
				$_g3 = tink_await_OutcomeTools::getOutcome($__t46, null);
				switch($_g3->index) {
				case 0:{
					$v3 = _hx_deref($_g3)->params[0];
					$__t46_result = $v3;
				}break;
				case 1:{
					$e3 = _hx_deref($_g3)->params[0];
					call_user_func_array($__return, array(tink_core_Outcome::Failure($e3)));
					return;
				}break;
				}
			}
			{
				$this6 = haxe_crypto_Base64::encode(haxe_io_Bytes::ofString($_gthis->connection->auth->password), null);
				$this7 = $_gthis->writeLine($this6);
				$this7->handle(array(new _hx_lambda(array(&$__return, &$_gthis), "smtpmailer_SmtpMailer_46"), 'execute'));
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e8 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e8)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_41(&$__return, &$__t9, &$_gthis, &$encoded, $__t14) {
	{
		try {
			$__t14_result = null;
			{
				$_g3 = tink_await_OutcomeTools::getOutcome($__t14, null);
				switch($_g3->index) {
				case 0:{
					$v3 = _hx_deref($_g3)->params[0];
					$__t14_result = $v3;
				}break;
				case 1:{
					$e5 = _hx_deref($_g3)->params[0];
					call_user_func_array($__t9, array($e5));
					return;
				}break;
				}
			}
			{
				$this5 = $_gthis->readLine(354);
				$this5->handle(array(new _hx_lambda(array(&$__return, &$__t9, &$_gthis, &$encoded), "smtpmailer_SmtpMailer_47"), 'execute'));
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e16 = $_ex_;
			{
				call_user_func_array($__t9, array($e16));
			}
		}
	}
}
function smtpmailer_SmtpMailer_42(&$__doCount, &$__iterator, &$__t13_continue, &$__t9, &$_gthis) {
	{
		$__doCount = $__doCount + 1;
		if($__doCount - 1 === 0) {
			while(true) {
				$user = $__iterator->next();
				{
					$this11 = $_gthis->writeLine("RCPT to: " . _hx_string_or_null($user->address));
					$this11->handle(array(new _hx_lambda(array(&$__t13_continue, &$__t9, &$_gthis), "smtpmailer_SmtpMailer_48"), 'execute'));
					unset($this11);
				}
				$__doCount = $__doCount - 1;
				if(!($__doCount !== 0)) {
					break;
				}
				unset($user);
			}
		}
	}
}
function smtpmailer_SmtpMailer_43(&$__return, &$_gthis) {
	{
		$_gthis->connected = true;
		call_user_func_array($__return, array(tink_core_Outcome::Success(tink_core_Noise::$Noise)));
		return;
	}
}
function smtpmailer_SmtpMailer_44(&$__t30) {
	{
		call_user_func($__t30);
	}
}
function smtpmailer_SmtpMailer_45(&$__return, &$__t32, $__t34) {
	{
		try {
			$__t34_result = null;
			{
				$_g3 = tink_await_OutcomeTools::getOutcome($__t34, null);
				switch($_g3->index) {
				case 0:{
					$v2 = _hx_deref($_g3)->params[0];
					$__t34_result = $v2;
				}break;
				case 1:{
					$e2 = _hx_deref($_g3)->params[0];
					call_user_func_array($__return, array(tink_core_Outcome::Failure($e2)));
					return;
				}break;
				}
			}
			call_user_func($__t32);
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e3 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e3)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_46(&$__return, &$_gthis, $__t47) {
	{
		try {
			$__t47_result = null;
			{
				$_g4 = tink_await_OutcomeTools::getOutcome($__t47, null);
				switch($_g4->index) {
				case 0:{
					$v4 = _hx_deref($_g4)->params[0];
					$__t47_result = $v4;
				}break;
				case 1:{
					$e4 = _hx_deref($_g4)->params[0];
					call_user_func_array($__return, array(tink_core_Outcome::Failure($e4)));
					return;
				}break;
				}
			}
			{
				$this8 = $_gthis->readLine(235);
				$this8->handle(array(new _hx_lambda(array(&$__return), "smtpmailer_SmtpMailer_49"), 'execute'));
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e7 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e7)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_47(&$__return, &$__t9, &$_gthis, &$encoded, $__t15) {
	{
		try {
			$__t15_result = null;
			{
				$_g4 = tink_await_OutcomeTools::getOutcome($__t15, null);
				switch($_g4->index) {
				case 0:{
					$v4 = _hx_deref($_g4)->params[0];
					$__t15_result = $v4;
				}break;
				case 1:{
					$e6 = _hx_deref($_g4)->params[0];
					call_user_func_array($__t9, array($e6));
					return;
				}break;
				}
			}
			{
				$this6 = tink_io__IdealSource_IdealSource_Impl_::fromString($encoded);
				$this7 = $_gthis->socket->output;
				$__t13_break1 = $this6->pipeSafelyTo($this7, null);
				$__t13_break1->handle(array(new _hx_lambda(array(&$__return, &$__t9, &$_gthis), "smtpmailer_SmtpMailer_50"), 'execute'));
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e15 = $_ex_;
			{
				call_user_func_array($__t9, array($e15));
			}
		}
	}
}
function smtpmailer_SmtpMailer_48(&$__t13_continue, &$__t9, &$_gthis, $__t22) {
	{
		try {
			$__t22_result = null;
			{
				$_g31 = tink_await_OutcomeTools::getOutcome($__t22, null);
				switch($_g31->index) {
				case 0:{
					$v9 = _hx_deref($_g31)->params[0];
					$__t22_result = $v9;
				}break;
				case 1:{
					$e17 = _hx_deref($_g31)->params[0];
					call_user_func_array($__t9, array($e17));
					return;
				}break;
				}
			}
			{
				$this12 = $_gthis->readLine(250);
				$this12->handle(array(new _hx_lambda(array(&$__t13_continue, &$__t9), "smtpmailer_SmtpMailer_51"), 'execute'));
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e20 = $_ex_;
			{
				call_user_func_array($__t9, array($e20));
			}
		}
	}
}
function smtpmailer_SmtpMailer_49(&$__return, $__t48) {
	{
		try {
			$__t48_result = null;
			{
				$_g5 = tink_await_OutcomeTools::getOutcome($__t48, null);
				switch($_g5->index) {
				case 0:{
					$v5 = _hx_deref($_g5)->params[0];
					$__t48_result = $v5;
				}break;
				case 1:{
					$e5 = _hx_deref($_g5)->params[0];
					call_user_func_array($__return, array(tink_core_Outcome::Failure($e5)));
					return;
				}break;
				}
			}
			call_user_func_array($__return, array(tink_core_Outcome::Success(tink_core_Noise::$Noise)));
			return;
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e6 = $_ex_;
			{
				call_user_func_array($__return, array(tink_core_Outcome::Failure($e6)));
			}
		}
	}
}
function smtpmailer_SmtpMailer_50(&$__return, &$__t9, &$_gthis, $__t21) {
	{
		try {
			$__t21_result = null;
			{
				$_g5 = tink_await_OutcomeTools::getOutcome(null, $__t21);
				switch($_g5->index) {
				case 0:{
					$v5 = _hx_deref($_g5)->params[0];
					$__t21_result = $v5;
				}break;
				case 1:{
					$e7 = _hx_deref($_g5)->params[0];
					call_user_func_array($__t9, array($e7));
					return;
				}break;
				}
			}
			{
				$__t16 = array(new _hx_lambda(array(&$__return, &$__t9, &$_gthis), "smtpmailer_SmtpMailer_52"), 'execute');
				if($__t21_result->index === 0) {
					call_user_func($__t16);
				} else {
					call_user_func_array($__t9, array("Could not write to stream"));
					return;
				}
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e14 = $_ex_;
			{
				call_user_func_array($__t9, array($e14));
			}
		}
	}
}
function smtpmailer_SmtpMailer_51(&$__t13_continue, &$__t9, $__t23) {
	{
		try {
			$__t23_result = null;
			{
				$_g41 = tink_await_OutcomeTools::getOutcome($__t23, null);
				switch($_g41->index) {
				case 0:{
					$v10 = _hx_deref($_g41)->params[0];
					$__t23_result = $v10;
				}break;
				case 1:{
					$e18 = _hx_deref($_g41)->params[0];
					call_user_func_array($__t9, array($e18));
					return;
				}break;
				}
			}
			call_user_func($__t13_continue);
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e19 = $_ex_;
			{
				call_user_func_array($__t9, array($e19));
			}
		}
	}
}
function smtpmailer_SmtpMailer_52(&$__return, &$__t9, &$_gthis) {
	{
		$this8 = $_gthis->writeLine("");
		$this8->handle(array(new _hx_lambda(array(&$__return, &$__t9, &$_gthis), "smtpmailer_SmtpMailer_53"), 'execute'));
	}
}
function smtpmailer_SmtpMailer_53(&$__return, &$__t9, &$_gthis, $__t18) {
	{
		try {
			$__t18_result = null;
			{
				$_g6 = tink_await_OutcomeTools::getOutcome($__t18, null);
				switch($_g6->index) {
				case 0:{
					$v6 = _hx_deref($_g6)->params[0];
					$__t18_result = $v6;
				}break;
				case 1:{
					$e8 = _hx_deref($_g6)->params[0];
					call_user_func_array($__t9, array($e8));
					return;
				}break;
				}
			}
			{
				$this9 = $_gthis->writeLine(".");
				$this9->handle(array(new _hx_lambda(array(&$__return, &$__t9, &$_gthis), "smtpmailer_SmtpMailer_54"), 'execute'));
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e13 = $_ex_;
			{
				call_user_func_array($__t9, array($e13));
			}
		}
	}
}
function smtpmailer_SmtpMailer_54(&$__return, &$__t9, &$_gthis, $__t19) {
	{
		try {
			$__t19_result = null;
			{
				$_g7 = tink_await_OutcomeTools::getOutcome($__t19, null);
				switch($_g7->index) {
				case 0:{
					$v7 = _hx_deref($_g7)->params[0];
					$__t19_result = $v7;
				}break;
				case 1:{
					$e9 = _hx_deref($_g7)->params[0];
					call_user_func_array($__t9, array($e9));
					return;
				}break;
				}
			}
			{
				$this10 = $_gthis->readLine(250);
				$this10->handle(array(new _hx_lambda(array(&$__return, &$__t9), "smtpmailer_SmtpMailer_55"), 'execute'));
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e12 = $_ex_;
			{
				call_user_func_array($__t9, array($e12));
			}
		}
	}
}
function smtpmailer_SmtpMailer_55(&$__return, &$__t9, $__t20) {
	{
		try {
			$__t20_result = null;
			{
				$_g8 = tink_await_OutcomeTools::getOutcome($__t20, null);
				switch($_g8->index) {
				case 0:{
					$v8 = _hx_deref($_g8)->params[0];
					$__t20_result = $v8;
				}break;
				case 1:{
					$e10 = _hx_deref($_g8)->params[0];
					call_user_func_array($__t9, array($e10));
					return;
				}break;
				}
			}
			call_user_func_array($__return, array(tink_core_Outcome::Success(tink_core_Noise::$Noise)));
			return;
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e11 = $_ex_;
			{
				call_user_func_array($__t9, array($e11));
			}
		}
	}
}
