<?php

// Generated by Haxe 3.4.4
class controller_HomeController extends ufront_web_Controller {
	public function __construct() {
		if(!php_Boot::$skip_constructor) {
		parent::__construct();
	}}
	public $testApi;
	public $mailApi;
	public function main() {
		$t = "Confidant Communications : Graphic Design, Website Design and Joomla Interactive Developer in Saskatoon, Saskatchewan";
		$obj = _hx_anonymous(array());
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		$tmp = new ufront_web_result_PartialViewResult(ufront_view__TemplateData_TemplateData_Impl_::setObject($this1, _hx_anonymous(array("title" => $t, "panel1classes" => "recessed0", "panel2classes" => "", "panel3classes" => ""))), null, null);
		$tmp1 = $tmp->addPartialString("subcontent", "", ufront_view_TemplatingEngines::get_haxe());
		$this2 = Type::getClassName(_hx_qtype("actions.ConfidantInterface"));
		return ufront_web_result_AddClientActionResult::addClientAction($tmp1, $this2, _hx_anonymous(array("msg" => $t)));
	}
	public function getHostName() {
		return $_SERVER['SERVER_NAME'];
	}
	public function about() {
		$t = "About Us : Confidant Communications";
		$d = _hx_anonymous(array("title" => $t, "portfolioItem" => null, "panel1classes" => "recessed0 recessed1", "panel2classes" => "recessed0", "panel3classes" => "", "gobackLink" => "http://" . _hx_string_or_null($this->getHostName()) . "/"));
		$obj = _hx_anonymous(array());
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		$tmp = new ufront_web_result_PartialViewResult(ufront_view__TemplateData_TemplateData_Impl_::setObject($this1, $d), null, null);
		$tmp1 = $tmp->addPartialString("subcontent", "", ufront_view_TemplatingEngines::get_haxe());
		$this2 = Type::getClassName(_hx_qtype("actions.ConfidantInterface"));
		return ufront_web_result_AddClientActionResult::addClientAction($tmp1, $this2, _hx_anonymous(array("msg" => $t)));
	}
	public function graphic() {
		$t = "Graphic Design in Saskatoon : Confidant Communications";
		$obj = _hx_anonymous(array());
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		$tmp = _hx_deref(new ufront_web_result_PartialViewResult(ufront_view__TemplateData_TemplateData_Impl_::setObject($this1, _hx_anonymous(array("title" => $t, "portfolioItem" => "", "panel1classes" => "recessed0 recessed1 recessed2", "panel2classes" => "recessed0 recessed1", "panel3classes" => "recessed0", "gobackLink" => "/about/"))), null, null))->addPartial("subcontent", "/about/graphic.html", null);
		$this2 = Type::getClassName(_hx_qtype("actions.ConfidantInterface"));
		return ufront_web_result_AddClientActionResult::addClientAction($tmp, $this2, _hx_anonymous(array("msg" => $t)));
	}
	public function joomla() {
		$t = "Joomla! Development and Training in Saskatoon : Confidant Communications";
		$obj = _hx_anonymous(array());
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		$tmp = _hx_deref(new ufront_web_result_PartialViewResult(ufront_view__TemplateData_TemplateData_Impl_::setObject($this1, _hx_anonymous(array("title" => $t, "portfolioItem" => "", "panel1classes" => "recessed0 recessed1 recessed2", "panel2classes" => "recessed0 recessed1", "panel3classes" => "recessed0", "gobackLink" => "/about/"))), null, null))->addPartial("subcontent", "/about/joomla.html", null);
		$this2 = Type::getClassName(_hx_qtype("actions.ConfidantInterface"));
		return ufront_web_result_AddClientActionResult::addClientAction($tmp, $this2, _hx_anonymous(array("msg" => $t)));
	}
	public function books() {
		$t = "Book Design, Book Marketing, and Book Publishing in Saskatoon : Confidant Communications";
		$obj = _hx_anonymous(array());
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		$tmp = _hx_deref(new ufront_web_result_PartialViewResult(ufront_view__TemplateData_TemplateData_Impl_::setObject($this1, _hx_anonymous(array("title" => $t, "portfolioItem" => "", "panel1classes" => "recessed0 recessed1 recessed2", "panel2classes" => "recessed0 recessed1", "panel3classes" => "recessed0", "gobackLink" => "/about/"))), null, null))->addPartial("subcontent", "/about/books.html", null);
		$this2 = Type::getClassName(_hx_qtype("actions.ConfidantInterface"));
		return ufront_web_result_AddClientActionResult::addClientAction($tmp, $this2, _hx_anonymous(array("msg" => $t)));
	}
	public function web() {
		$t = "Web Design in Saskatoon : Confidant Communications";
		$obj = _hx_anonymous(array());
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		$tmp = _hx_deref(new ufront_web_result_PartialViewResult(ufront_view__TemplateData_TemplateData_Impl_::setObject($this1, _hx_anonymous(array("title" => $t, "portfolioItem" => "", "panel1classes" => "recessed0 recessed1 recessed2", "panel2classes" => "recessed0 recessed1", "panel3classes" => "recessed0", "gobackLink" => "/about/"))), null, null))->addPartial("subcontent", "/about/web.html", null);
		$this2 = Type::getClassName(_hx_qtype("actions.ConfidantInterface"));
		return ufront_web_result_AddClientActionResult::addClientAction($tmp, $this2, _hx_anonymous(array("msg" => $t)));
	}
	public function interactive() {
		$t = "Interactive Development in Saskatoon : Confidant Communications";
		$obj = _hx_anonymous(array());
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		$tmp = _hx_deref(new ufront_web_result_PartialViewResult(ufront_view__TemplateData_TemplateData_Impl_::setObject($this1, _hx_anonymous(array("title" => $t, "portfolioItem" => "", "panel1classes" => "recessed0 recessed1 recessed2", "panel2classes" => "recessed0 recessed1", "panel3classes" => "recessed0", "gobackLink" => "/about/"))), null, null))->addPartial("subcontent", "/about/interactive.html", null);
		$this2 = Type::getClassName(_hx_qtype("actions.ConfidantInterface"));
		return ufront_web_result_AddClientActionResult::addClientAction($tmp, $this2, _hx_anonymous(array("msg" => $t)));
	}
	public function contact() {
		$t = "Contact Us : Confidant Communications";
		$d = _hx_anonymous(array("title" => $t, "portfolioItem" => null, "panel1classes" => "recessed0 recessed1", "panel2classes" => "recessed0", "panel3classes" => "", "gobackLink" => "http://" . _hx_string_or_null($this->getHostName()) . "/"));
		$obj = _hx_anonymous(array());
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		$tmp = new ufront_web_result_PartialViewResult(ufront_view__TemplateData_TemplateData_Impl_::setObject($this1, $d), null, null);
		$tmp1 = $tmp->addPartialString("subcontent", "", ufront_view_TemplatingEngines::get_haxe());
		$this2 = Type::getClassName(_hx_qtype("actions.ConfidantInterface"));
		return ufront_web_result_AddClientActionResult::addClientAction($tmp1, $this2, _hx_anonymous(array("msg" => $t)));
	}
	public function portfolio() {
		$_gthis = $this;
		$t = "Portfolio of Graphic Design and Website Development Projects : Confidant Communications";
		$path = "portfolio.json";
		return tink_core__Future_Future_Impl_::_tryMap($this->testApi->getJson($path), array(new _hx_lambda(array(&$_gthis, &$t), "controller_HomeController_0"), 'execute'));
	}
	public function returnPortfolioItem($id) {
		$t = "Portfolio : ";
		$t2 = " : Confidant Communications";
		return tink_core__Future_Future_Impl_::_tryMap($this->testApi->getItem($id), array(new _hx_lambda(array(&$t, &$t2), "controller_HomeController_1"), 'execute'));
	}
	public function processJson($pJson) {
		$parsed = haxe_Json::phpJsonDecode($pJson);
		return $parsed->items;
	}
	public function contactResult($args) {
		$t = "Contact : Confidant Communications";
		$returnHome = "<p style=\"text-align:center;\"><a href=\"/\" rel=\"pushstate\">Go back home now?</a></p>";
		return tink_core__Future_Future_Impl_::_tryMap($this->mailApi->doMail($args->email, $args->name, $args->message), array(new _hx_lambda(array(&$returnHome, &$t), "controller_HomeController_2"), 'execute'));
	}
	public function execute() {
		$uriParts = $this->context->actionContext->get_uriParts();
		$params = $this->context->request->get_params();
		$method = $this->context->request->get_httpMethod();
		$this->context->actionContext->controller = $this;
		$this->context->actionContext->action = "execute";
		try {
			$tmp = null;
			if(strtolower($method) === "get") {
				$tmp = 0 === $uriParts->length;
			} else {
				$tmp = false;
			}
			if($tmp) {
				$this->context->actionContext->action = "main";
				$this->context->actionContext->args = (new _hx_array(array()));
				$this->context->actionContext->get_uriParts()->splice(0, 0);
				$this1 = _hx_field(haxe_rtti_Meta::getFields(_hx_qtype("controller.HomeController")), "main")->wrapResult[0];
				$wrappingRequired = $this1;
				$result = $this->wrapResult($this->main(), $wrappingRequired);
				$this->setContextActionResultWhenFinished($result);
				return $result;
			} else {
				$tmp1 = null;
				$tmp2 = null;
				if(strtolower($method) === "get") {
					$tmp2 = 1 === $uriParts->length;
				} else {
					$tmp2 = false;
				}
				if($tmp2) {
					$tmp1 = $uriParts[0] === "about";
				} else {
					$tmp1 = false;
				}
				if($tmp1) {
					$this->context->actionContext->action = "about";
					$this->context->actionContext->args = (new _hx_array(array()));
					$this->context->actionContext->get_uriParts()->splice(0, 1);
					$this2 = _hx_field(haxe_rtti_Meta::getFields(_hx_qtype("controller.HomeController")), "about")->wrapResult[0];
					$wrappingRequired1 = $this2;
					$result1 = $this->wrapResult($this->about(), $wrappingRequired1);
					$this->setContextActionResultWhenFinished($result1);
					return $result1;
				} else {
					$tmp3 = null;
					$tmp4 = null;
					$tmp5 = null;
					if(strtolower($method) === "get") {
						$tmp5 = 2 === $uriParts->length;
					} else {
						$tmp5 = false;
					}
					if($tmp5) {
						$tmp4 = $uriParts[0] === "about";
					} else {
						$tmp4 = false;
					}
					if($tmp4) {
						$tmp3 = $uriParts[1] === "graphic-design-saskatoon";
					} else {
						$tmp3 = false;
					}
					if($tmp3) {
						$this->context->actionContext->action = "graphic";
						$this->context->actionContext->args = (new _hx_array(array()));
						$this->context->actionContext->get_uriParts()->splice(0, 2);
						$this3 = _hx_field(haxe_rtti_Meta::getFields(_hx_qtype("controller.HomeController")), "graphic")->wrapResult[0];
						$wrappingRequired2 = $this3;
						$result2 = $this->wrapResult($this->graphic(), $wrappingRequired2);
						$this->setContextActionResultWhenFinished($result2);
						return $result2;
					} else {
						$tmp6 = null;
						$tmp7 = null;
						$tmp8 = null;
						if(strtolower($method) === "get") {
							$tmp8 = 2 === $uriParts->length;
						} else {
							$tmp8 = false;
						}
						if($tmp8) {
							$tmp7 = $uriParts[0] === "about";
						} else {
							$tmp7 = false;
						}
						if($tmp7) {
							$tmp6 = $uriParts[1] === "joomla-development-saskatoon";
						} else {
							$tmp6 = false;
						}
						if($tmp6) {
							$this->context->actionContext->action = "joomla";
							$this->context->actionContext->args = (new _hx_array(array()));
							$this->context->actionContext->get_uriParts()->splice(0, 2);
							$this4 = _hx_field(haxe_rtti_Meta::getFields(_hx_qtype("controller.HomeController")), "joomla")->wrapResult[0];
							$wrappingRequired3 = $this4;
							$result3 = $this->wrapResult($this->joomla(), $wrappingRequired3);
							$this->setContextActionResultWhenFinished($result3);
							return $result3;
						} else {
							$tmp9 = null;
							$tmp10 = null;
							$tmp11 = null;
							if(strtolower($method) === "get") {
								$tmp11 = 2 === $uriParts->length;
							} else {
								$tmp11 = false;
							}
							if($tmp11) {
								$tmp10 = $uriParts[0] === "about";
							} else {
								$tmp10 = false;
							}
							if($tmp10) {
								$tmp9 = $uriParts[1] === "book-design-saskatoon";
							} else {
								$tmp9 = false;
							}
							if($tmp9) {
								$this->context->actionContext->action = "books";
								$this->context->actionContext->args = (new _hx_array(array()));
								$this->context->actionContext->get_uriParts()->splice(0, 2);
								$this5 = _hx_field(haxe_rtti_Meta::getFields(_hx_qtype("controller.HomeController")), "books")->wrapResult[0];
								$wrappingRequired4 = $this5;
								$result4 = $this->wrapResult($this->books(), $wrappingRequired4);
								$this->setContextActionResultWhenFinished($result4);
								return $result4;
							} else {
								$tmp12 = null;
								$tmp13 = null;
								$tmp14 = null;
								if(strtolower($method) === "get") {
									$tmp14 = 2 === $uriParts->length;
								} else {
									$tmp14 = false;
								}
								if($tmp14) {
									$tmp13 = $uriParts[0] === "about";
								} else {
									$tmp13 = false;
								}
								if($tmp13) {
									$tmp12 = $uriParts[1] === "web-design-saskatoon";
								} else {
									$tmp12 = false;
								}
								if($tmp12) {
									$this->context->actionContext->action = "web";
									$this->context->actionContext->args = (new _hx_array(array()));
									$this->context->actionContext->get_uriParts()->splice(0, 2);
									$this6 = _hx_field(haxe_rtti_Meta::getFields(_hx_qtype("controller.HomeController")), "web")->wrapResult[0];
									$wrappingRequired5 = $this6;
									$result5 = $this->wrapResult($this->web(), $wrappingRequired5);
									$this->setContextActionResultWhenFinished($result5);
									return $result5;
								} else {
									$tmp15 = null;
									$tmp16 = null;
									$tmp17 = null;
									if(strtolower($method) === "get") {
										$tmp17 = 2 === $uriParts->length;
									} else {
										$tmp17 = false;
									}
									if($tmp17) {
										$tmp16 = $uriParts[0] === "about";
									} else {
										$tmp16 = false;
									}
									if($tmp16) {
										$tmp15 = $uriParts[1] === "interactive-developer-saskatoon";
									} else {
										$tmp15 = false;
									}
									if($tmp15) {
										$this->context->actionContext->action = "interactive";
										$this->context->actionContext->args = (new _hx_array(array()));
										$this->context->actionContext->get_uriParts()->splice(0, 2);
										$this7 = _hx_field(haxe_rtti_Meta::getFields(_hx_qtype("controller.HomeController")), "interactive")->wrapResult[0];
										$wrappingRequired6 = $this7;
										$result6 = $this->wrapResult($this->interactive(), $wrappingRequired6);
										$this->setContextActionResultWhenFinished($result6);
										return $result6;
									} else {
										$tmp18 = null;
										$tmp19 = null;
										if(strtolower($method) === "get") {
											$tmp19 = 1 === $uriParts->length;
										} else {
											$tmp19 = false;
										}
										if($tmp19) {
											$tmp18 = $uriParts[0] === "contact";
										} else {
											$tmp18 = false;
										}
										if($tmp18) {
											$this->context->actionContext->action = "contact";
											$this->context->actionContext->args = (new _hx_array(array()));
											$this->context->actionContext->get_uriParts()->splice(0, 1);
											$this8 = _hx_field(haxe_rtti_Meta::getFields(_hx_qtype("controller.HomeController")), "contact")->wrapResult[0];
											$wrappingRequired7 = $this8;
											$result7 = $this->wrapResult($this->contact(), $wrappingRequired7);
											$this->setContextActionResultWhenFinished($result7);
											return $result7;
										} else {
											$tmp20 = null;
											$tmp21 = null;
											if(strtolower($method) === "get") {
												$tmp21 = 1 === $uriParts->length;
											} else {
												$tmp21 = false;
											}
											if($tmp21) {
												$tmp20 = $uriParts[0] === "portfolio";
											} else {
												$tmp20 = false;
											}
											if($tmp20) {
												$this->context->actionContext->action = "portfolio";
												$this->context->actionContext->args = (new _hx_array(array()));
												$this->context->actionContext->get_uriParts()->splice(0, 1);
												$this9 = _hx_field(haxe_rtti_Meta::getFields(_hx_qtype("controller.HomeController")), "portfolio")->wrapResult[0];
												$wrappingRequired8 = $this9;
												$result8 = $this->wrapResult($this->portfolio(), $wrappingRequired8);
												$this->setContextActionResultWhenFinished($result8);
												return $result8;
											} else {
												$tmp22 = null;
												$tmp23 = null;
												$tmp24 = null;
												if(strtolower($method) === "get") {
													$tmp24 = 2 === $uriParts->length;
												} else {
													$tmp24 = false;
												}
												if($tmp24) {
													$tmp23 = $uriParts[0] === "portfolio";
												} else {
													$tmp23 = false;
												}
												if($tmp23) {
													$tmp22 = strlen($uriParts[1]) > 0;
												} else {
													$tmp22 = false;
												}
												if($tmp22) {
													$id = $uriParts[1];
													$this->context->actionContext->action = "returnPortfolioItem";
													$this->context->actionContext->args = (new _hx_array(array($id)));
													$this->context->actionContext->get_uriParts()->splice(0, 2);
													$this10 = _hx_field(haxe_rtti_Meta::getFields(_hx_qtype("controller.HomeController")), "returnPortfolioItem")->wrapResult[0];
													$wrappingRequired9 = $this10;
													$result9 = $this->wrapResult($this->returnPortfolioItem($id), $wrappingRequired9);
													$this->setContextActionResultWhenFinished($result9);
													return $result9;
												} else {
													$tmp25 = null;
													$tmp26 = null;
													$tmp27 = null;
													if(strtolower($method) === "post") {
														$tmp27 = 2 === $uriParts->length;
													} else {
														$tmp27 = false;
													}
													if($tmp27) {
														$tmp26 = $uriParts[0] === "contact";
													} else {
														$tmp26 = false;
													}
													if($tmp26) {
														$tmp25 = $uriParts[1] === "send";
													} else {
														$tmp25 = false;
													}
													if($tmp25) {
														if(!$params->exists("email")) {
															$reason = "Missing parameter " . "email";
															$message = "Bad Request";
															if($reason !== null) {
																$message = _hx_string_or_null($message) . _hx_string_or_null((": " . _hx_string_or_null($reason)));
															}
															throw new HException(new tink_core_TypedError(400, $message, _hx_anonymous(array("fileName" => "HomeController.hx", "lineNumber" => 245, "className" => "controller.HomeController", "methodName" => "execute"))));
														}
														$_param_tmp_email = ufront_core__MultiValueMap_MultiValueMap_Impl_::get($params, "email");
														if(!$params->exists("name")) {
															$reason1 = "Missing parameter " . "name";
															$message1 = "Bad Request";
															if($reason1 !== null) {
																$message1 = _hx_string_or_null($message1) . _hx_string_or_null((": " . _hx_string_or_null($reason1)));
															}
															throw new HException(new tink_core_TypedError(400, $message1, _hx_anonymous(array("fileName" => "HomeController.hx", "lineNumber" => 245, "className" => "controller.HomeController", "methodName" => "execute"))));
														}
														$_param_tmp_name = ufront_core__MultiValueMap_MultiValueMap_Impl_::get($params, "name");
														if(!$params->exists("message")) {
															$reason2 = "Missing parameter " . "message";
															$message2 = "Bad Request";
															if($reason2 !== null) {
																$message2 = _hx_string_or_null($message2) . _hx_string_or_null((": " . _hx_string_or_null($reason2)));
															}
															throw new HException(new tink_core_TypedError(400, $message2, _hx_anonymous(array("fileName" => "HomeController.hx", "lineNumber" => 245, "className" => "controller.HomeController", "methodName" => "execute"))));
														}
														$_param_tmp_message = ufront_core__MultiValueMap_MultiValueMap_Impl_::get($params, "message");
														$args = _hx_anonymous(array("email" => $_param_tmp_email, "name" => $_param_tmp_name, "message" => $_param_tmp_message));
														$this->context->actionContext->action = "contactResult";
														$this->context->actionContext->args = (new _hx_array(array($args)));
														$this->context->actionContext->get_uriParts()->splice(0, 2);
														$this11 = _hx_field(haxe_rtti_Meta::getFields(_hx_qtype("controller.HomeController")), "contactResult")->wrapResult[0];
														$wrappingRequired10 = $this11;
														$result10 = $this->wrapResult($this->contactResult($args), $wrappingRequired10);
														$this->setContextActionResultWhenFinished($result10);
														return $result10;
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
			throw new HException(ufront_web_HttpError::pageNotFound(_hx_anonymous(array("fileName" => "HomeController.hx", "lineNumber" => 21, "className" => "controller.HomeController", "methodName" => "execute"))));
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e = $_ex_;
			{
				$tmp28 = "Uncaught error while executing " . Std::string($this->context->actionContext->controller) . ".";
				return ufront_core_SurpriseTools::asSurpriseError($e, _hx_string_or_null($tmp28) . _hx_string_or_null($this->context->actionContext->action) . "()", _hx_anonymous(array("fileName" => "HomeController.hx", "lineNumber" => 21, "className" => "controller.HomeController", "methodName" => "execute")));
			}
		}
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static function __meta__() { $args = func_get_args(); return call_user_func_array(self::$__meta__, $args); }
	static $__meta__;
	function __toString() { return 'controller.HomeController'; }
}
controller_HomeController::$__meta__ = _hx_anonymous(array("obj" => _hx_anonymous(array("rtti" => (new _hx_array(array((new _hx_array(array("testApi", "api.AsyncTestApi", ""))), (new _hx_array(array("mailApi", "api.MailApi", "")))))))), "fields" => _hx_anonymous(array("main" => _hx_anonymous(array("wrapResult" => (new _hx_array(array(3))))), "about" => _hx_anonymous(array("wrapResult" => (new _hx_array(array(3))))), "graphic" => _hx_anonymous(array("wrapResult" => (new _hx_array(array(3))), "template" => (new _hx_array(array("/home/about.html"))))), "joomla" => _hx_anonymous(array("wrapResult" => (new _hx_array(array(3))), "template" => (new _hx_array(array("/home/about.html"))))), "books" => _hx_anonymous(array("wrapResult" => (new _hx_array(array(3))), "template" => (new _hx_array(array("/home/about.html"))))), "web" => _hx_anonymous(array("wrapResult" => (new _hx_array(array(3))), "template" => (new _hx_array(array("/home/about.html"))))), "interactive" => _hx_anonymous(array("wrapResult" => (new _hx_array(array(3))), "template" => (new _hx_array(array("/home/about.html"))))), "contact" => _hx_anonymous(array("wrapResult" => (new _hx_array(array(3))))), "portfolio" => _hx_anonymous(array("wrapResult" => (new _hx_array(array(4))))), "returnPortfolioItem" => _hx_anonymous(array("wrapResult" => (new _hx_array(array(4))))), "contactResult" => _hx_anonymous(array("wrapResult" => (new _hx_array(array(4))), "template" => (new _hx_array(array("/home/contact.html")))))))));
function controller_HomeController_0(&$_gthis, &$t, $result) {
	{
		$d = $_gthis->processJson($result);
		$d1 = "http://" . _hx_string_or_null($_gthis->getHostName()) . "/";
		$obj = _hx_anonymous(array());
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		$tmp = new ufront_web_result_PartialViewResult(ufront_view__TemplateData_TemplateData_Impl_::setObject($this1, _hx_anonymous(array("title" => $t, "content" => $d, "portfolioItem" => null, "panel1classes" => "recessed0 recessed1", "panel2classes" => "recessed0", "panel3classes" => "", "gobackLink" => $d1))), null, null);
		$tmp1 = $tmp->addPartialString("subcontent", "", ufront_view_TemplatingEngines::get_haxe());
		$this2 = Type::getClassName(_hx_qtype("actions.ConfidantInterface"));
		return ufront_web_result_AddClientActionResult::addClientAction($tmp1, $this2, _hx_anonymous(array("msg" => $t)));
	}
}
function controller_HomeController_1(&$t, &$t2, $result) {
	{
		$d = _hx_string_or_null($t) . _hx_string_or_null($result->title) . _hx_string_or_null($t2);
		$d1 = _hx_anonymous(array("title" => $d, "content" => new _hx_array(array()), "portfolioItem" => $result, "panel1classes" => "recessed0 recessed1 recessed2", "panel2classes" => "recessed0 recessed1", "panel3classes" => "recessed0", "gobackLink" => "/portfolio/"));
		$obj = _hx_anonymous(array());
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		$tmp = new ufront_web_result_PartialViewResult(ufront_view__TemplateData_TemplateData_Impl_::setObject($this1, $d1), "portfolio.html", null);
		$tmp1 = $tmp->addPartialString("subcontent", "", ufront_view_TemplatingEngines::get_haxe());
		$this2 = Type::getClassName(_hx_qtype("actions.ConfidantInterface"));
		return ufront_web_result_AddClientActionResult::addClientAction($tmp1, $this2, _hx_anonymous(array("msg" => _hx_string_or_null($t) . _hx_string_or_null($result->title))));
	}
}
function controller_HomeController_2(&$returnHome, &$t, $result) {
	{
		$obj = _hx_anonymous(array());
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		$tmp = new ufront_web_result_PartialViewResult(ufront_view__TemplateData_TemplateData_Impl_::setObject($this1, _hx_anonymous(array("title" => $t, "portfolioItem" => null, "panel1classes" => "recessed0 recessed1 recessed2", "panel2classes" => "recessed0 recessed1", "panel3classes" => "recessed0", "gobackLink" => "/contact/"))), null, null);
		$tmp1 = _hx_string_or_null($result) . _hx_string_or_null($returnHome);
		$tmp2 = $tmp->addPartialString("subcontent", $tmp1, ufront_view_TemplatingEngines::get_haxe());
		$this2 = Type::getClassName(_hx_qtype("actions.ConfidantInterface"));
		return ufront_web_result_AddClientActionResult::addClientAction($tmp2, $this2, _hx_anonymous(array("msg" => _hx_string_or_null($t) . _hx_string_or_null($result))));
	}
}
