<?php

// Generated by Haxe 3.4.2
class controller_HomeController extends ufront_web_Controller {
	public function __construct() {
		if(!php_Boot::$skip_constructor) {
		parent::__construct();
	}}
	public $testApi;
	public function main() {
		$obj = _hx_anonymous(array());
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		$tmp = new ufront_web_result_PartialViewResult(ufront_view__TemplateData_TemplateData_Impl_::setObject($this1, _hx_anonymous(array("title" => "Confidant Communications : Graphic Design, Website Design and Joomla Interactive Developer in Saskatoon, Saskatchewan", "panel1classes" => "recessed0", "panel2classes" => "", "panel3classes" => ""))), null, null);
		$this2 = Type::getClassName(_hx_qtype("actions.ConfidantInterface"));
		return ufront_web_result_AddClientActionResult::addClientAction($tmp, $this2, _hx_anonymous(array("msg" => "simpleAction")));
	}
	public function getHostName() {
		return $_SERVER['SERVER_NAME'];
	}
	public function about() {
		$d = _hx_anonymous(array("title" => "Confidant Communications : About Us", "portfolioItem" => null, "panel1classes" => "recessed0 recessed1", "panel2classes" => "recessed0", "panel3classes" => "", "gobackLink" => "http://" . _hx_string_or_null($this->getHostName()) . "/"));
		$obj = _hx_anonymous(array());
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		$tmp = new ufront_web_result_PartialViewResult(ufront_view__TemplateData_TemplateData_Impl_::setObject($this1, $d), null, null);
		$this2 = Type::getClassName(_hx_qtype("actions.ConfidantInterface"));
		return ufront_web_result_AddClientActionResult::addClientAction($tmp, $this2, _hx_anonymous(array("msg" => "simpleAction")));
	}
	public function contact() {
		$d = _hx_anonymous(array("title" => "Confidant Communications : Contact Us", "portfolioItem" => null, "panel1classes" => "recessed0 recessed1", "panel2classes" => "recessed0", "panel3classes" => "", "gobackLink" => "http://" . _hx_string_or_null($this->getHostName()) . "/"));
		$obj = _hx_anonymous(array());
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		$tmp = new ufront_web_result_PartialViewResult(ufront_view__TemplateData_TemplateData_Impl_::setObject($this1, $d), null, null);
		$this2 = Type::getClassName(_hx_qtype("actions.ConfidantInterface"));
		return ufront_web_result_AddClientActionResult::addClientAction($tmp, $this2, _hx_anonymous(array("msg" => "simpleAction")));
	}
	public function portfolio() {
		$_gthis = $this;
		$path = "portfolio.json";
		return tink_core__Future_Future_Impl_::_tryMap($this->testApi->getJson($path), array(new _hx_lambda(array(&$_gthis), "controller_HomeController_0"), 'execute'));
	}
	public function returnPortfolioItem($id) {
		return tink_core__Future_Future_Impl_::_tryMap($this->testApi->getItem($id), array(new _hx_lambda(array(), "controller_HomeController_1"), 'execute'));
	}
	public function processJson($pJson) {
		$parsed = haxe_Json::phpJsonDecode($pJson);
		return $parsed->items;
	}
	public function execute() {
		$uriParts = $this->context->actionContext->get_uriParts();
		$params = $this->context->request->get_params();
		$method = $this->context->request->get_httpMethod();
		$this->context->actionContext->controller = $this;
		$this->context->actionContext->action = "execute";
		try {
			$tmp = null;
			if(strtolower($method) === "get") {
				$tmp = 0 === $uriParts->length;
			} else {
				$tmp = false;
			}
			if($tmp) {
				$this->context->actionContext->action = "main";
				$this->context->actionContext->args = (new _hx_array(array()));
				$this->context->actionContext->get_uriParts()->splice(0, 0);
				$this1 = _hx_field(haxe_rtti_Meta::getFields(_hx_qtype("controller.HomeController")), "main")->wrapResult[0];
				$wrappingRequired = $this1;
				$result = $this->wrapResult($this->main(), $wrappingRequired);
				$this->setContextActionResultWhenFinished($result);
				return $result;
			} else {
				$tmp1 = null;
				$tmp2 = null;
				if(strtolower($method) === "get") {
					$tmp2 = 1 === $uriParts->length;
				} else {
					$tmp2 = false;
				}
				if($tmp2) {
					$tmp1 = $uriParts[0] === "about";
				} else {
					$tmp1 = false;
				}
				if($tmp1) {
					$this->context->actionContext->action = "about";
					$this->context->actionContext->args = (new _hx_array(array()));
					$this->context->actionContext->get_uriParts()->splice(0, 1);
					$this2 = _hx_field(haxe_rtti_Meta::getFields(_hx_qtype("controller.HomeController")), "about")->wrapResult[0];
					$wrappingRequired1 = $this2;
					$result1 = $this->wrapResult($this->about(), $wrappingRequired1);
					$this->setContextActionResultWhenFinished($result1);
					return $result1;
				} else {
					$tmp3 = null;
					$tmp4 = null;
					if(strtolower($method) === "get") {
						$tmp4 = 1 === $uriParts->length;
					} else {
						$tmp4 = false;
					}
					if($tmp4) {
						$tmp3 = $uriParts[0] === "contact";
					} else {
						$tmp3 = false;
					}
					if($tmp3) {
						$this->context->actionContext->action = "contact";
						$this->context->actionContext->args = (new _hx_array(array()));
						$this->context->actionContext->get_uriParts()->splice(0, 1);
						$this3 = _hx_field(haxe_rtti_Meta::getFields(_hx_qtype("controller.HomeController")), "contact")->wrapResult[0];
						$wrappingRequired2 = $this3;
						$result2 = $this->wrapResult($this->contact(), $wrappingRequired2);
						$this->setContextActionResultWhenFinished($result2);
						return $result2;
					} else {
						$tmp5 = null;
						$tmp6 = null;
						if(strtolower($method) === "get") {
							$tmp6 = 1 === $uriParts->length;
						} else {
							$tmp6 = false;
						}
						if($tmp6) {
							$tmp5 = $uriParts[0] === "portfolio";
						} else {
							$tmp5 = false;
						}
						if($tmp5) {
							$this->context->actionContext->action = "portfolio";
							$this->context->actionContext->args = (new _hx_array(array()));
							$this->context->actionContext->get_uriParts()->splice(0, 1);
							$this4 = _hx_field(haxe_rtti_Meta::getFields(_hx_qtype("controller.HomeController")), "portfolio")->wrapResult[0];
							$wrappingRequired3 = $this4;
							$result3 = $this->wrapResult($this->portfolio(), $wrappingRequired3);
							$this->setContextActionResultWhenFinished($result3);
							return $result3;
						} else {
							$tmp7 = null;
							$tmp8 = null;
							$tmp9 = null;
							if(strtolower($method) === "get") {
								$tmp9 = 2 === $uriParts->length;
							} else {
								$tmp9 = false;
							}
							if($tmp9) {
								$tmp8 = $uriParts[0] === "portfolio";
							} else {
								$tmp8 = false;
							}
							if($tmp8) {
								$tmp7 = strlen($uriParts[1]) > 0;
							} else {
								$tmp7 = false;
							}
							if($tmp7) {
								$id = $uriParts[1];
								$this->context->actionContext->action = "returnPortfolioItem";
								$this->context->actionContext->args = (new _hx_array(array($id)));
								$this->context->actionContext->get_uriParts()->splice(0, 2);
								$this5 = _hx_field(haxe_rtti_Meta::getFields(_hx_qtype("controller.HomeController")), "returnPortfolioItem")->wrapResult[0];
								$wrappingRequired4 = $this5;
								$result4 = $this->wrapResult($this->returnPortfolioItem($id), $wrappingRequired4);
								$this->setContextActionResultWhenFinished($result4);
								return $result4;
							}
						}
					}
				}
			}
			throw new HException(ufront_web_HttpError::pageNotFound(_hx_anonymous(array("fileName" => "HomeController.hx", "lineNumber" => 19, "className" => "controller.HomeController", "methodName" => "execute"))));
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e = $_ex_;
			{
				$tmp10 = "Uncaught error while executing " . Std::string($this->context->actionContext->controller) . ".";
				return ufront_core_SurpriseTools::asSurpriseError($e, _hx_string_or_null($tmp10) . _hx_string_or_null($this->context->actionContext->action) . "()", _hx_anonymous(array("fileName" => "HomeController.hx", "lineNumber" => 19, "className" => "controller.HomeController", "methodName" => "execute")));
			}
		}
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static function __meta__() { $args = func_get_args(); return call_user_func_array(self::$__meta__, $args); }
	static $__meta__;
	function __toString() { return 'controller.HomeController'; }
}
controller_HomeController::$__meta__ = _hx_anonymous(array("obj" => _hx_anonymous(array("rtti" => (new _hx_array(array((new _hx_array(array("testApi", "api.AsyncTestApi", "")))))))), "fields" => _hx_anonymous(array("main" => _hx_anonymous(array("wrapResult" => (new _hx_array(array(3))))), "about" => _hx_anonymous(array("wrapResult" => (new _hx_array(array(3))))), "contact" => _hx_anonymous(array("wrapResult" => (new _hx_array(array(3))))), "portfolio" => _hx_anonymous(array("wrapResult" => (new _hx_array(array(4))))), "returnPortfolioItem" => _hx_anonymous(array("wrapResult" => (new _hx_array(array(4)))))))));
function controller_HomeController_0(&$_gthis, $result) {
	{
		$d = $_gthis->processJson($result);
		$d1 = _hx_anonymous(array("title" => "Confidant Communications : Portfolio of Graphic Design and Website Development Projects", "content" => $d, "portfolioItem" => null, "panel1classes" => "recessed0 recessed1", "panel2classes" => "recessed0", "panel3classes" => "", "gobackLink" => "http://" . _hx_string_or_null($_gthis->getHostName()) . "/"));
		$obj = _hx_anonymous(array());
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		$tmp = new ufront_web_result_PartialViewResult(ufront_view__TemplateData_TemplateData_Impl_::setObject($this1, $d1), null, null);
		$this2 = Type::getClassName(_hx_qtype("actions.ConfidantInterface"));
		return ufront_web_result_AddClientActionResult::addClientAction($tmp, $this2, _hx_anonymous(array("msg" => "simpleAction")));
	}
}
function controller_HomeController_1($result) {
	{
		$d = "Confidant Communications : Portfolio : " . _hx_string_or_null($result->title);
		$d1 = _hx_anonymous(array("title" => $d, "content" => new _hx_array(array()), "portfolioItem" => $result, "panel1classes" => "recessed0 recessed1 recessed2", "panel2classes" => "recessed0 recessed1", "panel3classes" => "recessed0", "gobackLink" => "/portfolio/"));
		$obj = _hx_anonymous(array());
		$this1 = null;
		if($obj !== null) {
			$this1 = $obj;
		} else {
			$this1 = _hx_anonymous(array());
		}
		$tmp = new ufront_web_result_PartialViewResult(ufront_view__TemplateData_TemplateData_Impl_::setObject($this1, $d1), "portfolio.html", null);
		$this2 = Type::getClassName(_hx_qtype("actions.ConfidantInterface"));
		return ufront_web_result_AddClientActionResult::addClientAction($tmp, $this2, _hx_anonymous(array("msg" => "simpleAction")));
	}
}
