<?php

// Generated by Haxe 3.4.4
class tink_core_OptionIter {
	public function __construct($o) {
		if(!php_Boot::$skip_constructor) {
		$this->alive = true;
		if($o->index === 0) {
			$v = _hx_deref($o)->params[0];
			$this->value = $v;
		} else {
			$this->alive = false;
		}
	}}
	public $value;
	public $alive;
	public function hasNext() {
		return $this->alive;
	}
	public function next() {
		$this->alive = false;
		return $this->value;
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return 'tink.core.OptionIter'; }
}
