<?php

// Generated by Haxe 3.4.4
class tink_io__Pipe_PipePart_Impl_ {
	public function __construct(){}
	static function _new($x) {
		$this1 = $x;
		return $this1;
	}
	static function ofIdealSource($s) {
		$this1 = $s;
		return $this1;
	}
	static function ofSource($s) {
		$this1 = $s;
		return $this1;
	}
	static function ofIdealSink($s) {
		$this1 = $s;
		return $this1;
	}
	static function ofSink($s) {
		$this1 = $s;
		return $this1;
	}
	function __toString() { return 'tink.io._Pipe.PipePart_Impl_'; }
}
