<?php

// Generated by Haxe 3.4.2
class ufront_web_upload_TmpFileUpload extends ufront_web_upload_BaseUpload implements ufront_web_upload_UFFileUpload{
	public function __construct($tmpFileName, $postName, $originalFileName, $size, $contentType = null) {
		if(!php_Boot::$skip_constructor) {
		parent::__construct($postName,haxe_io_Path::withoutDirectory($originalFileName),$size,$contentType);
		$this->tmpFileName = $tmpFileName;
	}}
	public $tmpFileName;
	public function getBytes() {
		if($this->attachedUpload !== null) {
			return $this->attachedUpload->getBytes();
		}
		try {
			return tink_core__Future_Future_Impl_::sync(tink_core_Outcome::Success(sys_io_File::getBytes($this->tmpFileName)));
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e = $_ex_;
			{
				return tink_core__Future_Future_Impl_::sync(tink_core_Outcome::Failure(ufront_web_HttpError::wrap($e, "Error during TmpFileUpload.getBytes()", _hx_anonymous(array("fileName" => "TmpFileUpload.hx", "lineNumber" => 49, "className" => "ufront.web.upload.TmpFileUpload", "methodName" => "getBytes")))));
			}
		}
	}
	public function getString($encoding = null) {
		if($encoding === null) {
			$encoding = "UTF-8";
		}
		if($this->attachedUpload !== null) {
			return $this->attachedUpload->getString($encoding);
		}
		try {
			return tink_core__Future_Future_Impl_::sync(tink_core_Outcome::Success(sys_io_File::getContent($this->tmpFileName)));
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e = $_ex_;
			{
				return tink_core__Future_Future_Impl_::sync(tink_core_Outcome::Failure(ufront_web_HttpError::wrap($e, "Error during TmpFileUpload.getString()", _hx_anonymous(array("fileName" => "TmpFileUpload.hx", "lineNumber" => 67, "className" => "ufront.web.upload.TmpFileUpload", "methodName" => "getString")))));
			}
		}
	}
	public function writeToFile($newFilePath) {
		if($this->attachedUpload !== null) {
			return $this->attachedUpload->writeToFile($newFilePath);
		}
		try {
			$directory = haxe_io_Path::directory($newFilePath);
			if(!file_exists($directory)) {
				$path = haxe_io_Path::addTrailingSlash($directory);
				$_p = null;
				$parts = (new _hx_array(array()));
				while(true) {
					$_p = haxe_io_Path::directory($path);
					if(!($path !== $_p)) {
						break;
					}
					$parts->unshift($path);
					$path = $_p;
				}
				{
					$_g = 0;
					while($_g < $parts->length) {
						$part = $parts[$_g];
						$_g = $_g + 1;
						$tmp = null;
						if(_hx_char_code_at($part, strlen($part) - 1) !== 58) {
							$tmp = !file_exists($part);
						} else {
							$tmp = false;
						}
						if($tmp) {
							@mkdir($part, 493);
						}
						unset($tmp,$part);
					}
				}
			}
			sys_io_File::copy($this->tmpFileName, $newFilePath);
			return ufront_core_SurpriseTools::success();
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e = $_ex_;
			{
				return tink_core__Future_Future_Impl_::sync(tink_core_Outcome::Failure(ufront_web_HttpError::wrap($e, "Error during TmpFileUpload.writeToFile()", _hx_anonymous(array("fileName" => "TmpFileUpload.hx", "lineNumber" => 87, "className" => "ufront.web.upload.TmpFileUpload", "methodName" => "writeToFile")))));
			}
		}
	}
	public function process($onData, $partSize = null) {
		if($this->attachedUpload !== null) {
			return $this->attachedUpload->process($onData, $partSize);
		}
		try {
			if($partSize === null) {
				$partSize = 8192;
			}
			$doneTrigger = new tink_core_FutureTrigger();
			$fh = sys_io_File::read($this->tmpFileName, null);
			$pos = 0;
			$readNext = null;
			$readNext = array(new _hx_lambda(array(&$doneTrigger, &$fh, &$onData, &$partSize, &$pos, &$readNext), "ufront_web_upload_TmpFileUpload_0"), 'execute');
			$readNext1 = $readNext;
			call_user_func($readNext1);
			return (property_exists($doneTrigger, "future") ? $doneTrigger->future: array($doneTrigger, "future"));
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e2 = $_ex_;
			{
				return tink_core__Future_Future_Impl_::sync(tink_core_Outcome::Failure(ufront_web_HttpError::wrap($e2, "Error during TmpFileUpload.process()", _hx_anonymous(array("fileName" => "TmpFileUpload.hx", "lineNumber" => 152, "className" => "ufront.web.upload.TmpFileUpload", "methodName" => "process")))));
			}
		}
	}
	public function deleteTemporaryFile() {
		try {
			{
				$path = $this->tmpFileName;
				unlink($path);
			}
			return tink_core_Outcome::Success(tink_core_Noise::$Noise);
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e = $_ex_;
			{
				return tink_core_Outcome::Failure(ufront_web_HttpError::wrap($e, "Error during TmpFileUpload.deleteTmpFile()", _hx_anonymous(array("fileName" => "TmpFileUpload.hx", "lineNumber" => 169, "className" => "ufront.web.upload.TmpFileUpload", "methodName" => "deleteTemporaryFile"))));
			}
		}
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return 'ufront.web.upload.TmpFileUpload'; }
}
function ufront_web_upload_TmpFileUpload_0(&$doneTrigger, &$fh, &$onData, &$partSize, &$pos, &$readNext) {
	{
		$final = false;
		$surprise = null;
		try {
			$bytes = $fh->read($partSize);
			$surprise = call_user_func_array($onData, array($bytes, $pos, $bytes->length));
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			if(($e = $_ex_) instanceof haxe_io_Eof){
				$final = true;
				$bytes1 = $fh->readAll($partSize);
				$surprise = call_user_func_array($onData, array($bytes1, $pos, $bytes1->length));
			}
			else { $e1 = $_ex_;
			{
				$surprise = tink_core__Future_Future_Impl_::sync(tink_core_Outcome::Failure(ufront_web_HttpError::wrap($e1, "Error during TmpFileUpload.process", _hx_anonymous(array("fileName" => "TmpFileUpload.hx", "lineNumber" => 132, "className" => "ufront.web.upload.TmpFileUpload", "methodName" => "process")))));
			}}
		}
		call_user_func_array($surprise, array(array(new _hx_lambda(array(&$doneTrigger, &$final, &$partSize, &$pos, &$readNext), "ufront_web_upload_TmpFileUpload_1"), 'execute')));
	}
}
function ufront_web_upload_TmpFileUpload_1(&$doneTrigger, &$final, &$partSize, &$pos, &$readNext, $outcome) {
	{
		switch($outcome->index) {
		case 0:{
			if($final === false) {
				$pos = $pos + $partSize;
				call_user_func($readNext);
			} else {
				$result = tink_core_Outcome::Success(tink_core_Noise::$Noise);
				if($doneTrigger->{"list"} !== null) {
					$list = $doneTrigger->{"list"};
					$doneTrigger->{"list"} = null;
					$doneTrigger->result = $result;
					tink_core__Callback_CallbackList_Impl_::invoke($list, $result);
					tink_core__Callback_CallbackList_Impl_::clear($list);
				}
			}
		}break;
		case 1:{
			$err = _hx_deref($outcome)->params[0];
			{
				$result1 = tink_core_Outcome::Failure($err);
				if($doneTrigger->{"list"} !== null) {
					$list1 = $doneTrigger->{"list"};
					$doneTrigger->{"list"} = null;
					$doneTrigger->result = $result1;
					tink_core__Callback_CallbackList_Impl_::invoke($list1, $result1);
					tink_core__Callback_CallbackList_Impl_::clear($list1);
				}
			}
		}break;
		}
	}
}
