<?php

// Generated by Haxe 3.4.4
class mtwin_mail_Part extends mtwin_mail_MetaPart {
	public function __construct($a = null, $b = null, $c = null) { if(!php_Boot::$skip_constructor) {
		parent::__construct($a,$b,$c);
	}}
	public function newPart($ctype) {
		$o = new mtwin_mail_Part($ctype, true, $this->charset);
		$this->addPart($o);
		return $o;
	}
	static function parseString($str) {
		$o = new mtwin_mail_Part(null, null, null);
		$o->parse($str, null);
		return $o;
	}
	function __toString() { return 'mtwin.mail.Part'; }
}
