<?php

// Generated by Haxe 3.4.4
class tink_core__Ref_Ref_Impl_ {
	public function __construct(){}
	static function _new() {
		$this1 = null;
		$this2 = (new _hx_array(array()));
		$this2->length = 1;
		$this1 = $this2;
		return $this1;
	}
	static function get_value($this1) {
		return $this1[0];
	}
	static function set_value($this1, $param) {
		return $this1[0] = $param;
	}
	static function toString($this1) {
		return "@[" . Std::string($this1[0]) . "]";
	}
	static function to($v) {
		$this1 = null;
		$this2 = (new _hx_array(array()));
		$this2->length = 1;
		$this1 = $this2;
		$ret = $this1;
		$ret[0] = $v;
		return $ret;
	}
	static $__properties__ = array("set_value" => "set_value","get_value" => "get_value");
	function __toString() { return 'tink.core._Ref.Ref_Impl_'; }
}
