<?php

// Generated by Haxe 3.4.4
class tink_core__Callback_CallbackList_Impl_ {
	public function __construct(){}
	static function _new() {
		$this1 = (new _hx_array(array()));
		return $this1;
	}
	static function get_length($this1) {
		return $this1->length;
	}
	static function add($this1, $cb) {
		$node = new tink_core__Callback_ListCell($cb, $this1);
		$this1->push($node);
		return $node;
	}
	static function invoke($this1, $data) {
		$_g = 0;
		$_g1 = $this1->copy();
		while($_g < $_g1->length) {
			$cell = $_g1[$_g];
			$_g = $_g + 1;
			if($cell->cb !== null) {
				tink_core__Callback_Callback_Impl_::invoke((property_exists($cell, "cb") ? $cell->cb: array($cell, "cb")), $data);
			}
			unset($cell);
		}
	}
	static function clear($this1) {
		$_g = 0;
		$_g1 = $this1->splice(0, $this1->length);
		while($_g < $_g1->length) {
			$cell = $_g1[$_g];
			$_g = $_g + 1;
			$cell->clear();
			unset($cell);
		}
	}
	static $__properties__ = array("get_length" => "get_length");
	function __toString() { return 'tink.core._Callback.CallbackList_Impl_'; }
}
