<?php

// Generated by Haxe 3.4.4
class tink_core__Callback_LinkPair implements tink_core__Callback_LinkObject{
	public function __construct($a, $b) {
		if(!php_Boot::$skip_constructor) {
		$this->dissolved = false;
		$this->a = $a;
		$this->b = $b;
	}}
	public $a;
	public $b;
	public $dissolved;
	public function dissolve() {
		if(!$this->dissolved) {
			$this->dissolved = true;
			{
				$this1 = $this->a;
				if($this1 !== null) {
					$this1->dissolve();
				}
			}
			{
				$this2 = $this->b;
				if($this2 !== null) {
					$this2->dissolve();
				}
			}
		}
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return 'tink.core._Callback.LinkPair'; }
}
