<?php

// Generated by Haxe 3.4.4
class tink_io__Worker_EagerWorker implements tink_io_WorkerObject{
	public function __construct() {}
	public function work($task) {
		return new tink_core__Future_SyncFuture(new tink_core__Lazy_LazyConst($task->get()));
	}
	function __toString() { return 'tink.io._Worker.EagerWorker'; }
}
