<?php

// Generated by Haxe 3.4.4
class ufront_app_DefaultUfrontClientConfiguration {
	public function __construct(){}
	static function get() {
		$tmp = CompileTimeClassList::get("null,true,ufront.web.Controller");
		$tmp1 = CompileTimeClassList::get("null,true,ufront.api.UFApi");
		$tmp2 = CompileTimeClassList::get("null,true,ufront.web.client.UFClientAction");
		$tmp3 = ufront_view_TemplatingEngines::$all;
		return _hx_anonymous(array("indexController" => _hx_qtype("ufront.app.DefaultUfrontController"), "urlRewrite" => true, "basePath" => "/", "remotingPath" => "/", "disableBrowserTrace" => false, "controllers" => $tmp, "apis" => $tmp1, "clientActions" => $tmp2, "viewEngine" => _hx_qtype("ufront.view.HttpViewEngine"), "templatingEngines" => $tmp3, "viewPath" => "/view/", "defaultLayout" => null, "sessionImplementation" => _hx_qtype("ufront.web.session.VoidSession"), "requestMiddleware" => (new _hx_array(array())), "responseMiddleware" => (new _hx_array(array())), "errorHandlers" => (new _hx_array(array(new ufront_web_ErrorPageHandler()))), "authImplementation" => _hx_qtype("ufront.auth.NobodyAuthHandler")));
	}
	function __toString() { return 'ufront.app.DefaultUfrontClientConfiguration'; }
}
