<?php

// Generated by Haxe 3.4.4
class tink_await_OutcomeTools {
	public function __construct(){}
	static function getOutcome($outcome = null, $value = null) {
		if($outcome === null) {
			return tink_core_Outcome::Success($value);
		}
		return $outcome;
	}
	function __toString() { return 'tink.await.OutcomeTools'; }
}
